#!/bin/bash

# ==============================================================================
# Aluminion - Bacterial WGS Pipeline
# ==============================================================================

# Detectar la ruta donde se encuentra este script aluminion.sh
SCRIPT_DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )"

# Definir la ruta de los scripts auxiliares (por defecto la subcarpeta scripts/)
SCRIPTS_PATH="${ALUMINION_SCRIPTS:-$SCRIPT_DIR/scripts}"


set -euo pipefail

# ==============================================================================
# DEFAULT PARAMETERS
# ==============================================================================
THREADS_TOTAL=30
RUN_NAME=""
BASE_DIR="/home/usuario/Seqs/Servicio"
SEQ_LIST_INPUT=""
DB_DIR="/home/usuario/Databases"
PHASTEST_DIR="${ALUMINION_PHASTEST_DIR:-$HOME/Programs/phastest-docker}"
MINKNOW_DIR="${ALUMINION_MINKNOW_DIR:-/var/lib/minknow/data}"

# Docker image versions — update here after testing a new release
MOBSUITE_IMAGE="kbessonov/mob_suite:3.0.3"
COPLA_IMAGE="rpalcab/copla:1.0"

# ------------------------------------------------------------------------------
# QC and filtering thresholds (overridable via CLI flags below)
# ------------------------------------------------------------------------------
# Minimum size in MB for a per-sample concatenated FASTQ to enter the pipeline.
# Files below this size usually reflect a failed barcode or undersequenced sample.
MIN_READ_MB=135
# Chopper read-level quality filtering (Q-score, minimum length, 5' headcrop bp).
CHOPPER_MIN_QUALITY=12
CHOPPER_MIN_LENGTH=300
CHOPPER_HEADCROP=20
# Abricate AMR-gene calling thresholds (percent identity / coverage).
ABRICATE_MIN_ID=75
ABRICATE_MIN_COV=75
# Wall-clock limit for a single Flye assembly, as a `timeout` duration (30m, 4h, ...).
# A contaminated or otherwise pathological sample can make Flye spin forever inside
# "Extending reads" instead of exiting with an error: it never returns, so the
# assembly-failure handler below never runs and an unattended batch stalls for good.
# On timeout the sample is treated exactly like a Flye failure (skipped, recorded in
# the warnings summary) so the rest of the run — and the rest of the batch — proceeds.
# Set to 0 to disable the limit and wait indefinitely (legacy behaviour).
FLYE_TIMEOUT="${ALUMINION_FLYE_TIMEOUT:-4h}"

# Disjointig-stage subsampling for high-coverage samples. Flye's "Extending reads"
# stage costs time superlinearly in coverage, and ONT runs on a good library
# routinely land at 150-180x — far past the point where extra reads add assembly
# information. --asm-coverage makes Flye use only its longest reads for that stage
# (all reads are still used for the repeat graph and polishing, so contiguity and
# consensus quality are unaffected); it requires --genome-size to know what depth
# to subsample to. Empty = do not pass either flag (Flye's own default: use
# everything). ALUMINION_FLYE_ASM_COVERAGE=50 with a 5.2m genome size is the
# upstream-recommended setting for bacterial ONT assemblies.
FLYE_ASM_COVERAGE="${ALUMINION_FLYE_ASM_COVERAGE:-}"
FLYE_GENOME_SIZE="${ALUMINION_FLYE_GENOME_SIZE:-5.2m}"

show_help() {
    cat << EOF

Aluminion: Automated pipeline for bacterial genomes (Oxford Nanopore)

Usage: aluminion -r <run_name> [options]

Mandatory options:
  -r, --run       Name of the run folder generated by MinKNOW.

Additional options:
  -b, --db-dir    Path to the main Databases directory.
                  (Default: /home/usuario/Databases)
  -t, --threads   Number of threads/cores to use. (Default: 30)
  -l, --list      Path to the list_seq.tsv file.
  -d, --dir       Base working directory to save the analysis.
  -p, --phastest-dir  Path to the local Phastest docker-compose folder.
                  (Default: \$ALUMINION_PHASTEST_DIR or ~/Programs/phastest-docker)
  -m, --minknow-dir   Path to the MinKNOW data root directory.
                  (Default: \$ALUMINION_MINKNOW_DIR or /var/lib/minknow/data)
  --init-db       First run: create data_seq.tsv and data_analysis.tsv from scratch.
                  Also triggered automatically if those files do not exist.
  --resume        Resume a previously interrupted run. Each step checks whether
                  its output already exists and skips it if so. Use after any
                  mid-run failure to avoid repeating completed work.
  --skip-import-from-minknow
                  Skip importing data from the MinKNOW data tree. Assumes the run
                  folder already contains fastq_pass/ (with per-barcode subfolders)
                  and, optionally, final_summary_*.txt / report_*.json copied
                  there manually or by an external import. The pipeline will
                  abort with a clear error if fastq_pass/ is missing.
                  (--no-minknow is kept as a back-compat alias.)
  --unique-run    Self-contained single-run mode. Skips every interaction with
                  the shared repository (<BASE_DIR>/repository or --repo): no read
                  accumulator directory is created, no reads are copied there, and
                  \`is_repeated\` samples are processed as fresh runs (the prior reads
                  cannot be concatenated without the repository). Use it for one-off
                  projects, when no shared repository exists, or to protect an
                  existing one from being touched by a run you don't fully
                  trust yet.
  --skip-preprocessing  Skip read QC and filtering (NanoPlot + Chopper). Requires a
                  previous run to have completed this step (01_reads/, 02_filter/,
                  and samples file must exist). NOTE: the default end-of-run cleanup
                  prunes those reads; if they were pruned, regenerate them with
                  --just-preprocessing first (this flag will abort with a clear error).
  --skip-kraken   Skip Kraken2 read-level classification.
  --skip-abr      Skip Abricate AMR and virulence (VFDB) gene screens.
  --skip-typing   Skip all typing tools: GAMBIT, MLST, Kleborate, ECTyper.
  --skip-integrons  Skip Integron_Finder and integron parsing.
  --skip-plasmids   Skip Copla plasmid typing (MOB-suite always runs).
  --skip-phages     Skip Phastest prophage detection.
  --polish-batchsize <N>  Override dorado polish --batchsize. Lower this (e.g. 8 or 4)
                  if the GPU runs out of memory ("CUDA out of memory" / "no kernel image"
                  errors) at the default batch size. Omit to use dorado's default.

QC and filtering thresholds (override sensible defaults):
  --min-read-mb <N>       Minimum concatenated FASTQ size in MB to enter the pipeline. (Default: ${MIN_READ_MB})
  --chopper-q <N>         Chopper minimum read Q-score. (Default: ${CHOPPER_MIN_QUALITY})
  --chopper-len <N>       Chopper minimum read length (bp). (Default: ${CHOPPER_MIN_LENGTH})
  --chopper-headcrop <N>  Chopper 5' headcrop in bp. (Default: ${CHOPPER_HEADCROP})
  --abricate-minid <N>    Abricate minimum % identity for AMR calls. (Default: ${ABRICATE_MIN_ID})
  --abricate-mincov <N>   Abricate minimum % coverage for AMR calls. (Default: ${ABRICATE_MIN_COV})
  --flye-timeout <DUR>    Wall-clock limit per Flye assembly, as a \`timeout\` duration
                  (e.g. 90m, 4h). A sample that exceeds it is treated as a Flye failure
                  and skipped, so one pathological sample cannot stall an unattended
                  batch forever. Use 0 to wait indefinitely. (Default: ${FLYE_TIMEOUT})
  --flye-asm-coverage <N> Use only the longest reads, down to N-fold coverage, for Flye's
                  disjointig stage ("Extending reads"), which is where high-coverage
                  samples stall. All reads are still used for the repeat graph and
                  polishing, so contiguity and consensus are unaffected. Requires a
                  genome size; 50 is the upstream recommendation for bacteria.
                  Empty = pass neither flag. (Default: ${FLYE_ASM_COVERAGE:-(unset)})
  --flye-genome-size <S>  Estimated genome size for --flye-asm-coverage, in Flye's
                  notation (e.g. 5.2m). Ignored unless --flye-asm-coverage is set.
                  (Default: ${FLYE_GENOME_SIZE})
  --retry-failed-assembly Clear the run's record of samples that previously failed to
                  assemble, so --resume attempts them again. Without this flag a known
                  unassemblable sample is skipped on resumed runs instead of burning the
                  full --flye-timeout on every pass.

Cross-run MGE alerts (match this run's plasmids/integrons against a cumulative
repository to flag epidemiologically relevant recurrences):
  --repo PATH           Path to the MGE repository directory. If omitted, defaults
                        to \$BASE_DIR/repository so the repository lives next to
                        your runs. Use a shared/external path to pool across hosts.
  --init-repo           Create the repository structure at --repo (idempotent).
                        Safe to pass on every run; only the first call builds it.
  --alert-new-priority  Also raise alerts for first-occurrence MGEs that carry a
                        priority resistance/virulence gene (not just recurrences).
  --no-alerts           Skip the cross-run MGE alerts step entirely.

Disk usage and input layout:
  --keep-everything     Do not prune intermediate files at the end of a complete run.
                        By default Aluminion removes Flye staging dirs, the per-assembly
                        BLASTn DB, Kraken2 .out streams, and the per-sample reads in
                        01_reads/ and 02_filter/ (regenerable from the retained
                        fastq_pass/ with --just-preprocessing).
  --require-run-list    Disable the parent-directory list_seq.tsv fallback; force this
                        run to use a list_seq.tsv located inside the run folder (or -l).
                        Set automatically by aluminion_batch.sh for recurrent analyses.

Parallelism (per-sample steps; set as environment variables, not flags):
  Several light, independent per-sample steps run as bounded parallel pools to
  avoid leaving cores idle. CPU-saturating steps (Flye, Bakta, dorado polish,
  Integron_Finder) stay sequential on purpose. Defaults are conservative for a
  single mechanical HDD (too many concurrent streams thrash the disk); raise them
  on SSD/NVMe or many-core hosts. Phastest stays sequential regardless.
    ALUMINION_PAR_FILTER    Chopper read filtering.        (Default: 4)
    ALUMINION_PAR_QC        NanoPlot pre/post-filter QC.   (Default: 4)
    ALUMINION_PAR_ABRICATE  Abricate AMR + virulence.      (Default: 8)
    ALUMINION_PAR_MOBSUITE  MOB-suite plasmid recon.       (Default: 2)
    ALUMINION_PAR_COPLA     Copla plasmid typing.          (Default: 3)
    ALUMINION_COPLA_CPUS    Docker --cpus quota per Copla container, capping the
                            image's baked-in 20 threads. (Default: threads/PAR_COPLA)
  Example: ALUMINION_PAR_FILTER=8 ALUMINION_PAR_ABRICATE=16 aluminion -r RUN ...
  pigz is used automatically for FASTQ compression when installed (gzip fallback).

Early-stop flags (run only up to the named stage, then exit):
  --just-preprocessing  Stop after read QC and filtering. Output: filtered FASTQ in 02_filter/.
  --just-assembly       Stop after assembly, polishing, and QUAST. Output: FASTA in 03_assemblies/.
  -h, --help      Show this help message and exit.

Example:
  aluminion -r BAC_2025_NOV_25 -b /mnt/data/Databases -t 60

EOF
}

log()       { echo -e "\n\033[1;32m[$(date +'%Y-%m-%d %H:%M:%S')] $1\033[0m"; }
error_log() { echo -e "\n\033[1;31m[ERROR] $1\033[0m"; }
warn()      { echo -e "\033[1;33m[WARNING] $1\033[0m"; }
# Returns true if --resume is active and the sentinel file or directory already exists
resume_done() { [ -n "$RESUME" ] && { [ -f "$1" ] || [ -d "$1" ]; }; }

# Returns true if --resume is active and EVERY named path exists as a regular,
# non-empty FILE. Use this — never resume_done on a directory — whenever the
# output directory is created by the tool (or by our own `mkdir -p`) *before* the
# work inside it finishes. `resume_done <dir>` is true the instant a sample
# starts, so a sample interrupted mid-run (Ctrl-C, OOM, power cut, a batch moving
# on after an error) is silently treated as complete on the next --resume, and its
# missing results are then indistinguishable from a genuine biological negative.
# That exact failure mode cost us Phastest samples (see phastest_done) and the
# same shape exists for every directory-sentinel step.
resume_files_done() {
    [ -n "$RESUME" ] || return 1
    local f
    for f in "$@"; do
        [ -s "$f" ] || return 1
    done
    return 0
}

# ------------------------------------------------------------------------------
# Bounded-concurrency helper for embarrassingly-parallel per-sample steps.
# ------------------------------------------------------------------------------
# Many per-sample steps (NanoPlot, Chopper, Abricate, MOB-suite, Copla) are
# independent and light enough that running them one-by-one leaves most cores
# idle. This helper overlaps a bounded number of them at once. CPU-saturating
# steps that already use every core (Flye, Bakta, dorado polish, Integron_Finder)
# are deliberately NOT parallelised — doing so would only oversubscribe the CPU.
#
# IMPORTANT: background jobs run in subshells, so a job body CANNOT mutate parent
# shell state (the failed_* arrays). Only use this for steps whose job body writes
# solely to its own per-sample output files and needs no parent bookkeeping.
#
# Usage:
#     par_reset                                   # before the loop
#     for i in ...; do { work "$i"; } & par_wait <MAX>; done
#     par_drain                                   # after the loop (or later)
#
# Implementation: track the PIDs of the jobs WE launch in an array, and wait only on
# those specific PIDs — never a bare `wait`/`wait -n`.
#   * Why not `while (( $(jobs -rp|wc -l) >= MAX ))`: command substitution `$(...)` forks
#     a subshell with an EMPTY job table, so `jobs` there always reports zero and the
#     throttle never engages.
#   * Why not a bare `wait` in par_drain: stdout/stderr are piped to a `tee -a` child via
#     `exec > >(tee ...)` (process substitution). A bare `wait` (and `wait -n` with no
#     args) also waits on that logger child, which never exits until the script ends — so
#     the pipeline HANGS FOREVER. It is most visible on --resume, when every per-sample
#     step is skipped, no jobs are launched, and tee is the only remaining child. Waiting
#     on explicit PIDs sidesteps tee and any unrelated background job entirely.
# par_wait blocks on the OLDEST in-flight PID (FIFO) when at cap; `wait <pid>` works on
# every bash (unlike `wait -n <pid...>`, which needs bash >= 5.1). For these homogeneous,
# light per-sample jobs the head-of-line cost is negligible. set -e safety: a finished
# job's non-zero exit would abort the run under errexit, so we swallow it with `|| true`;
# each job body is responsible for its own errors.
_par_pids=()
par_reset() { _par_pids=(); }
par_wait()  {
    # Must be called immediately after `... &` so $! is that job's PID.
    _par_pids+=("$!")
    if [ "${#_par_pids[@]}" -ge "$1" ]; then
        wait "${_par_pids[0]}" 2>/dev/null || true
        _par_pids=("${_par_pids[@]:1}")          # drop the reaped (oldest) PID
    fi
}
par_drain() {
    [ "${#_par_pids[@]}" -gt 0 ] && wait "${_par_pids[@]}" 2>/dev/null || true
    _par_pids=()
}

# Prune large, non-reusable intermediates after a fully completed run. Disabled by
# --keep-everything. Only ever called at the very end of a complete run (the early
# --just-* exits return before this point), so the deleted files are no longer needed
# by any downstream step. fastq_pass/ is intentionally retained, which is what makes
# the per-sample reads in 01_reads/ and 02_filter/ disposable: they can be regenerated
# from fastq_pass/ with --just-preprocessing. All removals are per-sample and use -f/-rf
# so a missing target (e.g. a sample that skipped an optional step) is a silent no-op.
cleanup_run_artifacts() {
    log "Pruning intermediate files to save disk (pass --keep-everything to retain them)..."
    local i
    for i in $(cat samples 2>/dev/null); do
        # Flye staging directories (assembly graph + final assembly.fasta are kept)
        rm -rf "03_assemblies/${i}/00-assembly" \
               "03_assemblies/${i}/10-consensus" \
               "03_assemblies/${i}/20-repeat" \
               "03_assemblies/${i}/30-contigger" \
               "03_assemblies/${i}/40-polishing" \
               "03_assemblies/${i}/deconcat/multimer_mapping"
        # BLASTn nucleotide DBs: the ISfinder screen builds one on
        # 08_Anotacion/<s>/mob_recon/chromosome.fasta (sidecar *.n* files), and
        # deconcat builds per-contig DBs under 03_assemblies/<s>/deconcat/blastn/.
        rm -f "08_Anotacion/${i}/mob_recon/chromosome.fasta".n*
        rm -rf "03_assemblies/${i}/deconcat/blastn"
        # Kraken2 per-read classification stream (the .report summary is kept)
        rm -f "04_taxonomies/kraken2/${i}.out"
        # Per-sample reads — regenerable from the retained fastq_pass/ via --just-preprocessing
        rm -f "01_reads/${i}.fastq.gz" "02_filter/${i}.fastq.gz"
    done
    rm -rf .temp_dorado_models*
}

# ERR trap: with set -e the script exits silently on any non-zero command. This
# trap fires *before* the exit so the log records exactly which line and which
# command died, instead of leaving the user with an empty "Polishing..." trail.
trap 'rc=$?; error_log "Aborted at line ${BASH_LINENO[0]} (exit ${rc}) — last command: ${BASH_COMMAND}"' ERR

# Tracks samples that completed assembly but failed optional refinement / visualization steps
failed_polish=()
failed_deconcat=()
failed_circlator=()
failed_bandage=()
failed_typing=()
failed_phages=()

# ==============================================================================
# COMMAND LINE ARGUMENT PARSING
# ==============================================================================

RESUME=""
STOP_AFTER=""
SKIP_PREPROCESSING=""
SKIP_PHAGES=""
SKIP_INTEGRONS=""
SKIP_PLASMIDS=""
SKIP_TYPING=""
SKIP_KRAKEN=""
SKIP_ABR=""
INIT_DB=""
POLISH_BATCHSIZE=""
NO_MINKNOW=""
UNIQUE_RUN=""
REPO=""
INIT_REPO=""
ALERT_NEW_PRIORITY=""
NO_ALERTS=""
# Keep all intermediate files instead of pruning them at the end of a complete run.
KEEP_EVERYTHING=""
# Clear the per-run record of samples Flye could not assemble, forcing a retry on
# --resume. Must be initialised: `set -u` aborts on an unset variable reference.
RETRY_FAILED_ASSEMBLY=""
# Forbid the parent-directory list_seq.tsv fallback. Set by aluminion_batch.sh so
# that, in recurrent multi-folder analyses, each run is forced to carry its own
# list_seq.tsv inside the run folder (otherwise barcodes/sample IDs would collide
# across runs that silently share a single parent-level sheet).
REQUIRE_RUN_LIST=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -r|--run) RUN_NAME="$2"; shift ;;
        -b|--db-dir) DB_DIR="$2"; shift ;;
        -t|--threads) THREADS_TOTAL="$2"; shift ;;
        -l|--list) SEQ_LIST_INPUT="$2"; shift ;;
        -d|--dir) BASE_DIR="$2"; shift ;;
        -p|--phastest-dir) PHASTEST_DIR="$2"; shift ;;
        -m|--minknow-dir) MINKNOW_DIR="$2"; shift ;;
        --resume) RESUME=true ;;
        # Flags for skipping steps
        --skip-preprocessing) SKIP_PREPROCESSING=true ;;
        --skip-phages) SKIP_PHAGES="--skip-phages" ;;
        --skip-integrons) SKIP_INTEGRONS="--skip-integrons" ;;
        --skip-plasmids) SKIP_PLASMIDS="--skip-plasmids" ;;
        --skip-typing) SKIP_TYPING="--skip-typing" ;;
        --skip-kraken) SKIP_KRAKEN="--skip-kraken" ;;
        --skip-abr) SKIP_ABR="--skip-abr" ;;
        --init-db) INIT_DB="--init" ;;
        --polish-batchsize) POLISH_BATCHSIZE="$2"; shift ;;
        # Skip importing fastq_pass/ + reports from the MinKNOW data tree (the run
        # folder must already contain them). --no-minknow is kept as a back-compat alias.
        --skip-import-from-minknow|--no-minknow) NO_MINKNOW=true ;;
        --unique-run) UNIQUE_RUN=true ;;
        --keep-everything) KEEP_EVERYTHING=true ;;
        --require-run-list) REQUIRE_RUN_LIST=true ;;
        # Cross-run MGE alert flags
        --repo) REPO="$2"; shift ;;
        --init-repo) INIT_REPO=true ;;
        --alert-new-priority) ALERT_NEW_PRIORITY="--alert-new-priority" ;;
        --no-alerts) NO_ALERTS=true ;;
        # QC threshold overrides
        --min-read-mb)       MIN_READ_MB="$2"; shift ;;
        --chopper-q)         CHOPPER_MIN_QUALITY="$2"; shift ;;
        --chopper-len)       CHOPPER_MIN_LENGTH="$2"; shift ;;
        --chopper-headcrop)  CHOPPER_HEADCROP="$2"; shift ;;
        --abricate-minid)    ABRICATE_MIN_ID="$2"; shift ;;
        --abricate-mincov)   ABRICATE_MIN_COV="$2"; shift ;;
        --flye-timeout)      FLYE_TIMEOUT="$2"; shift ;;
        --flye-asm-coverage) FLYE_ASM_COVERAGE="$2"; shift ;;
        --flye-genome-size)  FLYE_GENOME_SIZE="$2"; shift ;;
        --retry-failed-assembly) RETRY_FAILED_ASSEMBLY=true ;;
        # Early-stop flags
        --just-preprocessing) STOP_AFTER="preprocessing" ;;
        --just-assembly) STOP_AFTER="assembly" ;;
        -h|--help) show_help; exit 0 ;;
        *) error_log "Unknown parameter: $1"; show_help; exit 1 ;;
    esac
    shift
done

if [ -z "$RUN_NAME" ]; then
    error_log "The -r / --run parameter is mandatory."
    show_help; exit 1
fi

# ------------------------------------------------------------------------------
# Parallelism widths for embarrassingly-parallel per-sample steps (see par_* above).
# Defaults are deliberately conservative because the typical production storage is a
# single mechanical HDD: too many concurrent read/write streams cause seek thrashing
# that erases the speedup. Override any of these via environment variable if your
# storage is SSD/NVMe or you have many more cores. CPU-saturating steps (Flye, Bakta,
# dorado polish, Integron_Finder) are NOT listed here on purpose.
# ------------------------------------------------------------------------------
PAR_FILTER="${ALUMINION_PAR_FILTER:-4}"        # Chopper filtering (gunzip|chopper|gzip pipe)
PAR_QC="${ALUMINION_PAR_QC:-4}"                # NanoPlot read QC (pre + post filter)
PAR_ABRICATE="${ALUMINION_PAR_ABRICATE:-8}"    # Abricate AMR/VFDB (single-thread BLAST, light I/O)
PAR_MOBSUITE="${ALUMINION_PAR_MOBSUITE:-2}"    # MOB-suite Docker (BLAST-heavy; each still multi-threaded)
PAR_COPLA="${ALUMINION_PAR_COPLA:-3}"          # Copla Docker (per plasmid contig)
# Copla's internal thread counts are baked into the rpalcab/copla:1.0 image and
# cannot be patched from the host: `docker run -v $(pwd):/tmp` mounts only the run
# directory, so the copy of the Copla source in ~/Programs/copla is NOT what runs
# (bin/check_conjugation_systems.sh there sets a bare THREADS=20, no ${THREADS:-20},
# so there is no env knob to override either). With PAR_COPLA=3 that is 3 x 20 = 60
# threads competing for 36 cores — the oversubscription behind the observed load of
# ~118. The one lever available from outside the image is Docker's own CPU quota, so
# cap each container. Default keeps the pool at or below the host's core count.
COPLA_CPUS="${ALUMINION_COPLA_CPUS:-$(( THREADS_TOTAL / PAR_COPLA ))}"
[ "$COPLA_CPUS" -lt 1 ] && COPLA_CPUS=1
# Per-job thread budget for steps that remain multi-threaded while parallelised, so
# the pool as a whole does not oversubscribe the CPU. Floor at 1 thread.
THREADS_FILTER=$(( THREADS_TOTAL / PAR_FILTER ));     [ "$THREADS_FILTER"   -lt 1 ] && THREADS_FILTER=1
THREADS_MOBSUITE=$(( THREADS_TOTAL / PAR_MOBSUITE )); [ "$THREADS_MOBSUITE" -lt 1 ] && THREADS_MOBSUITE=1

# Resolve relative paths before any cd changes the working directory
[ -n "$SEQ_LIST_INPUT" ] && SEQ_LIST_INPUT="$(readlink -f "$SEQ_LIST_INPUT")"
[ -n "$BASE_DIR"       ] && BASE_DIR="$(readlink -f "$BASE_DIR")"

# MGE repository: default to <BASE_DIR>/repository so it sits next to the runs.
# Resolve to an absolute path too; the repo may not exist yet on a first run, so
# fall back to the literal value if readlink can't canonicalise it.
[ -z "$REPO" ] && REPO="${BASE_DIR}/repository"
REPO="$(readlink -f "$REPO" 2>/dev/null || echo "$REPO")"

if [ ! -d "$DB_DIR" ]; then
    error_log "Database directory not found: $DB_DIR. Please check the -b parameter."
    exit 1
fi

# ==============================================================================
# DEPENDENCY CHECKS
# ==============================================================================
# samtools, datamash, blast, etc. are checked at runtime inside their conda envs
for dep in docker dorado; do
    command -v "$dep" >/dev/null 2>&1 || { error_log "Required tool '$dep' not found in PATH. Install it before running the pipeline."; exit 1; }
done

if ! command -v docker >/dev/null 2>&1; then
    error_log "Docker not found. Required for MOB-suite, Copla, and Phastest. Install Docker and ensure the daemon is running."
    exit 1
fi

# Phastest inputs preflight: the docker container runs as root and stamps
# phastest_inputs/<sample>.fasta with root:root ownership. A previous run that
# aborted before its cleanup leaves root-owned residue that blocks the next
# `cp` with "Permiso denegado". The runtime fix (rm -f + cp -f in the Phastest
# loop) handles per-sample residue gracefully, but if the DIRECTORY itself
# became unwritable we want to fail in seconds, not after Chopper+Flye+Bakta.
# Skipped when phages are disabled via --skip-phages.
if [ -z "${SKIP_PHAGES}" ] && [ -d "${PHASTEST_DIR}/phastest_inputs" ] \
        && [ ! -w "${PHASTEST_DIR}/phastest_inputs" ]; then
    error_log "${PHASTEST_DIR}/phastest_inputs is not writable by $(id -un)."
    error_log "Likely owned by root after a prior Phastest run. Fix:"
    error_log "  sudo chown -R $(id -u):$(id -g) ${PHASTEST_DIR}/phastest_inputs"
    error_log "Or pass --skip-phages to disable the Phastest stage for this run."
    exit 1
fi

WORKDIR="${BASE_DIR}/${RUN_NAME}"

# Databases routing
KRAKEN_DB="${DB_DIR}/Kraken"
GAMBIT_DB="${DB_DIR}/gambit"
BAKTA_DB="${DB_DIR}/bakta"
MEGARES_DB="${DB_DIR}/megares/sequences"
ISFINDER_DB="${DB_DIR}/ISfinder/ISfinder-nucl.fasta"

# Conda Initialization
if [ -f "$HOME/mambaforge/etc/profile.d/conda.sh" ]; then
    source "$HOME/mambaforge/etc/profile.d/conda.sh"
elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
else
    error_log "Could not find conda.sh initialization script."
    exit 1
fi

# ==============================================================================
# DIRECTORY AND DATA PREPARATION
# ==============================================================================
mkdir -p "$WORKDIR"
LOG_FILE="${WORKDIR}/aluminion_$(date +'%Y%m%d_%H%M%S').log"
exec > >(tee -a "$LOG_FILE") 2>&1

log "Starting Aluminion for run: $RUN_NAME"
log "Log file: $LOG_FILE"
cd "$WORKDIR"

# Copy MinKNOW metadata files (small, always needed). Skipped under --no-minknow
# when the run folder is already a self-contained import. The .minknow_import_done
# sentinel (written after a complete fastq_pass/ import below) lets --resume skip the
# whole MinKNOW import on a re-run, so a finished folder is not re-copied from scratch.
if [ -z "$NO_MINKNOW" ]; then
    if resume_done "fastq_pass/.minknow_import_done"; then
        log "  [resume] MinKNOW metadata already imported, skipping."
    else
        cp "${MINKNOW_DIR}/${RUN_NAME}/no_sample_id/"*/final_summary_*.txt . 2>/dev/null || true
        cp "${MINKNOW_DIR}/${RUN_NAME}/no_sample_id/"*/report_*.json      . 2>/dev/null || true
    fi
fi

# Resolve list_seq.tsv with the following precedence:
#   1. --list <path>            (explicit override)
#   2. <run folder>/list_seq.tsv (lives next to the reads — best for batch processing)
#   3. <parent folder>/list_seq.tsv (legacy single-run layout — copy into the run folder)
# Errors out with a populated template if none of the three are present.
# Under --require-run-list (set by aluminion_batch.sh for recurrent multi-folder runs)
# step 3 is disabled: every run MUST carry its own list_seq.tsv to avoid sample/barcode
# collisions between runs that would otherwise share one parent-level sheet.
if [ -n "$SEQ_LIST_INPUT" ] && [ -f "$SEQ_LIST_INPUT" ]; then
    cp "$SEQ_LIST_INPUT" "list_seq.tsv"
elif [ -f "list_seq.tsv" ]; then
    log "Using list_seq.tsv already present in the run folder."
elif [ -n "$REQUIRE_RUN_LIST" ]; then
    error_log "No list_seq.tsv inside the run folder ${WORKDIR}, and the parent-directory"
    error_log "fallback is disabled (--require-run-list). In recurrent/batch analyses each"
    error_log "run must carry its own list_seq.tsv. Place it in the run folder and re-run."
    exit 1
elif [ -f "${BASE_DIR}/list_seq.tsv" ]; then
    log "Using list_seq.tsv from the parent directory: ${BASE_DIR}/list_seq.tsv"
    cp "${BASE_DIR}/list_seq.tsv" "list_seq.tsv"
fi

if [ ! -f "list_seq.tsv" ]; then
    echo -e "Lab_id\tStrain\tID\tBarcode\tDNA_conc\tis_repeated" > list_seq.tsv
    error_log "Empty 'list_seq.tsv' created. Fill it out and re-run."
    exit 1
fi

# Auto-translate legacy Spanish column headers (Cultivo, Cepa, ID, Barcode, Conc, Repetida)
# to the current English schema. Earlier versions of the pipeline shipped Spanish names;
# this keeps old lab sheets working without forcing the user to edit them manually.
# Field order is preserved — only the header row is rewritten.
#
# Detection is by CONTENT, not by an exact prefix: the anchored '^(Cultivo|Cepa)\b'
# this used to test failed on the sheets the lab actually exports from Excel, whose
# first field is "Nº Cultivo" (and third "ID único" — accented, with a space). The
# header was therefore left in Spanish, aluminion_reporter.py's key_col='ID' never
# matched, no 'Sample' column was created, and the run died at the QC merge with
# KeyError: 'Sample' AFTER every sample had already been assembled and annotated.
# So: match if any known Spanish marker appears anywhere in the header line, and
# require that the English schema is NOT already in place.
list_header=$(head -n 1 list_seq.tsv | tr -d '\r')
# NOTE: the guard uses $'\t' (bash ANSI-C quoting), not '\t' inside the pattern —
# GNU grep -E does not honour \t as an escape, it matches a literal 't', so
# '(^|\t)Lab_id' would silently never match the English header.
if ! echo "$list_header" | grep -qE "^Lab_id($(printf '\t')|$)" \
   && echo "$list_header" | grep -qiE 'Cultivo|Cepario|Cepa|ID[[:space:]]*(único|unico)|Repetir|\[DNA\]'; then
    warn "list_seq.tsv uses legacy Spanish column names — auto-translating to English (Lab_id, Strain, ID, Barcode, DNA_conc, is_repeated)."
    {
        echo -e "Lab_id\tStrain\tID\tBarcode\tDNA_conc\tis_repeated"
        tail -n +2 list_seq.tsv | tr -d '\r'
    } > list_seq.tsv.translated
    mv list_seq.tsv.translated list_seq.tsv
fi

# With MinKNOW import skipped, the run folder must already contain a populated
# fastq_pass/. Otherwise, copy only the barcode subfolders referenced in
# list_seq.tsv (col 4) from the MinKNOW data tree into <run>/fastq_pass/.
# `tr -d '\r'` strips CRLF line endings that appear when list_seq.tsv is exported
# from Excel on Windows — without it, "01\r" would not match any printf %02d output.
if [ -n "$NO_MINKNOW" ]; then
    # fastq_pass/ is only ever dereferenced later by the read-concatenation loop
    # inside the preprocessing block, and only for a sample where resume_done() is
    # false. It is NOT needed at all when --skip-preprocessing is set (that block
    # never runs), and it is not needed under --resume if every listed sample
    # already has its concatenated reads staged in 01_reads/<id>.fastq.gz (e.g. a
    # project where reads were concatenated and named by hand or by an external
    # pipeline, never through this script's own fastq_pass/ import). Don't demand
    # fastq_pass/ in those cases — it would never be read anyway.
    _fastq_pass_needed=true
    if [ -n "$SKIP_PREPROCESSING" ]; then
        _fastq_pass_needed=false
    elif [ -n "$RESUME" ]; then
        _fastq_pass_needed=false
        while IFS=$'\t' read -r _fp_cult _fp_cep _fp_id _fp_bc _fp_dna _fp_rep; do
            [ -z "$_fp_id" ] && continue
            if [ ! -s "01_reads/${_fp_id}.fastq.gz" ]; then
                _fastq_pass_needed=true
                break
            fi
        done < <(tail -n +2 list_seq.tsv | tr -d '\r')
    fi
    if [ "$_fastq_pass_needed" = true ] && { [ ! -d "fastq_pass" ] || [ -z "$(ls -A fastq_pass 2>/dev/null)" ]; }; then
        error_log "--skip-import-from-minknow set but ${WORKDIR}/fastq_pass/ is missing or empty."
        error_log "Either populate fastq_pass/ with per-barcode subfolders, drop --skip-import-from-minknow,"
        error_log "or — if 01_reads/<ID>.fastq.gz is already staged for every sample — add --resume so the"
        error_log "read-concatenation step is skipped and fastq_pass/ is never required."
        exit 1
    fi
    if [ -d "fastq_pass" ] && [ -n "$(ls -A fastq_pass 2>/dev/null)" ]; then
        log "Using existing fastq_pass/ inside the run folder (MinKNOW import skipped)."
    else
        log "fastq_pass/ not required: reads already staged in 01_reads/ (--resume) or --skip-preprocessing is set."
    fi
    unset _fastq_pass_needed
elif resume_done "fastq_pass/.minknow_import_done"; then
    # A previous run already imported every referenced barcode into fastq_pass/.
    # Re-copying with cp -r would overwrite identical files and thrash the disk for
    # no gain, so on --resume we trust the completed import and move on.
    log "  [resume] fastq_pass/ already imported from MinKNOW, skipping copy."
else
    mkdir -p fastq_pass
    # `|| true` after the pipeline (not just on `ls`) is required under
    # `set -o pipefail`: when the glob matches nothing, `ls` exits 2 (discarded to
    # /dev/null) and, even though the downstream `head -n1` exits 0, pipefail makes
    # the *pipeline's* status the rightmost non-zero — i.e. 2 — which propagated
    # into this command-substitution assignment and aborted the whole run via the
    # ERR trap, before ever reaching the "MinKNOW directory not found" warning
    # below that is supposed to handle exactly this (non-fatal) case.
    FASTQ_SRC=$(ls -d "${MINKNOW_DIR}/${RUN_NAME}/no_sample_id/"*/fastq_pass 2>/dev/null | head -n1 || true)
    if [ -n "$FASTQ_SRC" ]; then
        tail -n +2 list_seq.tsv \
            | tr -d '\r' \
            | awk -F'\t' '{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $4); print $4}' \
            | grep -Ev '^[[:space:]]*$|^[xX]$' \
            | sort -u \
            | while read -r bc; do
                # Force base-10: printf treats a leading-zero value like "08"/"09" as
                # octal, where 8 and 9 are invalid digits ("invalid octal number").
                # 10#$bc strips that interpretation so zero-padded barcodes work.
                padded=$(printf "%02d" "$((10#$bc))")
                src="${FASTQ_SRC}/barcode${padded}"
                if [ -d "$src" ]; then
                    cp -r "$src" fastq_pass/
                else
                    log "Warning: barcode${padded} not found in MinKNOW fastq_pass — skipping."
                fi
            done
        # Mark the import complete so a later --resume skips it. Written only after the
        # copy loop, so an interrupted import (no sentinel) is correctly retried.
        touch fastq_pass/.minknow_import_done
    else
        log "Warning: MinKNOW fastq_pass directory not found. Continuing without copying reads."
    fi
fi

mkdir -p 01_reads/QC 02_filter/QC 03_assemblies/quast 04_taxonomies/{kraken2,gtdb} 05_plasmids 08_Anotacion 09_phages 10_ices 11_integrons
# Cross-run shared repository. This is the SAME directory the MGE alert system uses
# ($REPO, default <BASE_DIR>/repository), unified so there is a single shared store
# instead of the old split (legacy bash "repositorio" held only the is_repeated read
# accumulator; Python "repository" holds the plasmid/integron indices). Only 01_reads/
# is created here — the MGE subdirs (plasmids/, integrons/, sketches/) are created and
# populated by mge_repository.py during the alert step. Under --unique-run the shared
# store is left untouched so the run stays isolated.
if [ -z "$UNIQUE_RUN" ]; then
    mkdir -p "${REPO}/01_reads"
fi

# ==============================================================================
# PIPELINE EXECUTION
# ==============================================================================

# 1. Read preparation and QC/filtering
if [ -z "$SKIP_PREPROCESSING" ]; then
    echo -e "ID\tR1\tR2\tLongFastQ\tFast5\tGenomeSize\tFasta" > samplesheet.tsv

    # Strip CRLF (Excel-exported TSVs) before reading fields. Without this, the last
    # field of each line keeps a trailing \r that breaks printf, file lookups, and grep.
    tail -n +2 list_seq.tsv | tr -d '\r' | while IFS=$'\t' read -r cult cep id bc c rep; do
        [ -z "$id" ] && continue
        # Trim leading/trailing whitespace from the barcode in case the TSV has padded cells.
        bc="${bc#"${bc%%[![:space:]]*}"}"
        bc="${bc%"${bc##*[![:space:]]}"}"
        # Zero-pad barcode to match MinKNOW's two-digit directory naming (barcode01, barcode09…).
        # The copy step above already pads with printf "%02d"; this keeps the two in sync.
        # 10#$bc forces base-10 so a zero-padded "08"/"09" is not misread as octal.
        padded_bc=$(printf "%02d" "$((10#$bc))")
        if resume_done "01_reads/${id}.fastq.gz"; then
            log "  [resume] Read concat: ${id} already done, skipping."
        elif [ -z "$rep" ]; then
            # Fresh sample — concatenate the per-barcode FASTQs from this run only.
            cat fastq_pass/barcode${padded_bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
            if [ -z "$UNIQUE_RUN" ]; then
                cp 01_reads/${id}.fastq.gz "${REPO}/01_reads/${id}.fastq.gz"
            fi
        else
            # is_repeated sample. In repository-aware mode, prepend the prior reads
            # stored in the shared repository. Under --unique-run (or when the
            # repository exists but lacks prior reads for this sample), fall back to
            # the new reads alone and warn so the user knows the merge didn't happen.
            if [ -z "$UNIQUE_RUN" ] && [ -f "${REPO}/01_reads/${id}.fastq.gz" ]; then
                cat "${REPO}/01_reads/${id}.fastq.gz" fastq_pass/barcode${padded_bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
                cp 01_reads/${id}.fastq.gz "${REPO}/01_reads/${id}.fastq.gz"
            else
                if [ -n "$UNIQUE_RUN" ]; then
                    warn "  Sample ${id} is marked is_repeated but --unique-run is active — using new reads only (no concat with the repository)."
                else
                    warn "  Sample ${id} is marked is_repeated but no prior reads found in the repository — using new reads only."
                fi
                cat fastq_pass/barcode${padded_bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
                if [ -z "$UNIQUE_RUN" ]; then
                    cp 01_reads/${id}.fastq.gz "${REPO}/01_reads/${id}.fastq.gz"
                fi
            fi
        fi
        echo -e "${id}\t\t\t$PWD/01_reads/${id}.fastq.gz\t\t" >> samplesheet.tsv
    done
    # Build the sample list as the INTERSECTION of (a) the IDs declared in
    # list_seq.tsv and (b) the per-sample FASTQs on disk that pass the size filter.
    #
    # Scanning 01_reads/ alone (the old behaviour) made `samples` a function of disk
    # state instead of the sample sheet, so list_seq.tsv was authoritative only on a
    # sample's FIRST pass. Once 01_reads/<id>.fastq.gz existed, deleting a row from
    # list_seq.tsv had no effect: the find picked the leftover FASTQ back up and every
    # --resume re-queued the sample for assembly. That is exactly how a sample removed
    # from the sheet kept being handed to Flye. Intersecting makes the sheet
    # authoritative on every pass — dropping a row now really drops the sample —
    # while keeping the size filter as the quality gate it was meant to be.
    awk -F'\t' 'NR>1 {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $3); if ($3 != "") print $3}' \
        list_seq.tsv | tr -d '\r' | sort -u > .listed_ids
    find 01_reads -type f -name "*.fastq.gz" -size "+${MIN_READ_MB}M" -exec basename {} .fastq.gz \; \
        | sort -u > .reads_on_disk
    # Stage the new list, then validate it BEFORE replacing `samples`. Writing the find
    # result straight into `samples` destroyed it whenever the scan came back empty —
    # which is the normal state of a completed run whose 01_reads/ was pruned by the
    # end-of-run cleanup. A --resume over such a run (e.g. a loop re-resuming every
    # historical run) truncated `samples` to zero rows and then aborted, losing the
    # record of which samples the run contained.
    comm -12 .listed_ids .reads_on_disk > .samples_new

    # Reads present and big enough, but no longer declared in the sheet: almost always
    # a row the user deliberately removed (bad sequencing, contaminated sample). Say so
    # explicitly, because silently ignoring a 400MB FASTQ would otherwise look like a bug.
    dropped_ids=$(comm -13 .listed_ids .reads_on_disk | tr '\n' ' ')
    if [ -n "${dropped_ids// /}" ]; then
        log "Reads on disk not listed in list_seq.tsv — excluded from this run: ${dropped_ids}"
    fi
    rm -f .listed_ids .reads_on_disk

    if [ ! -s .samples_new ]; then
        rm -f .samples_new
        if [ -s samples ]; then
            error_log "No reads in 01_reads/ pass the ${MIN_READ_MB}MB filter, but this run already has a"
            error_log "'samples' file with $(wc -l < samples) sample(s) — the reads were most likely pruned by the"
            error_log "end-of-run cleanup. The existing 'samples' file was left untouched."
            error_log "Regenerate the reads with --just-preprocessing, or re-run with --skip-preprocessing"
            error_log "to reuse the existing results without touching the reads."
        else
            error_log "No samples in list_seq.tsv have reads in 01_reads/ passing the ${MIN_READ_MB}MB filter."
        fi
        exit 1
    fi
    mv .samples_new samples

    conda activate aluminion_reads

    # Chrome (used by NanoPlot's plot renderer) requires --no-sandbox on headless Linux servers.
    # Glob across the common conda installations (mambaforge / miniforge3 / miniconda3) so
    # the wrapper works regardless of which conda flavour the user installed.
    CHROME_REAL=""
    for conda_root in "$HOME/mambaforge" "$HOME/miniforge3" "$HOME/miniconda3"; do
        # `ls` returns 2 when the glob has no match; under `set -o pipefail` that
        # exit code propagates through `| head -1` and kills the script via `set -e`
        # before the loop can try the next conda root. `|| true` neutralises it.
        candidate=$(ls "$conda_root/envs/aluminion_reads/lib/python"*/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome 2>/dev/null | head -1 || true)
        if [ -n "$candidate" ]; then
            CHROME_REAL="$candidate"
            break
        fi
    done
    if [ -n "$CHROME_REAL" ] && [ -x "$CHROME_REAL" ]; then
        CHROME_WRAPPER="${WORKDIR}/.chrome_wrapper"
        printf '#!/bin/bash\nexec "%s" --no-sandbox --disable-gpu --disable-dev-shm-usage "$@"\n' "$CHROME_REAL" > "$CHROME_WRAPPER"
        chmod +x "$CHROME_WRAPPER"
        export BROWSER_PATH="$CHROME_WRAPPER"
    fi

    # Prefer pigz for (de)compression when present — it parallelises the gzip stage
    # that otherwise bottlenecks each Chopper pipe on a single core. Falls back to
    # gzip/gunzip so a run on an env without pigz still works unchanged.
    if command -v pigz >/dev/null 2>&1; then
        DECOMP="pigz -dc"; COMP="pigz -p ${THREADS_FILTER}"
    else
        DECOMP="gunzip -c"; COMP="gzip"
    fi

    log "Filtering (Chopper, up to ${PAR_FILTER} samples in parallel)..."
    par_reset
    for i in $(cat samples); do
        resume_done "02_filter/${i}.fastq.gz" && { log "  [resume] Chopper: ${i} done, skipping."; continue; }
        # Each pipe writes only its own 02_filter/${i}.fastq.gz, so concurrent jobs
        # cannot corrupt each other. Bounded by PAR_FILTER to keep the mechanical-disk
        # read/write streams from thrashing. Per-job threads reduced (THREADS_FILTER).
        {
            $DECOMP 01_reads/${i}.fastq.gz \
                | chopper -q $CHOPPER_MIN_QUALITY -l $CHOPPER_MIN_LENGTH --headcrop $CHOPPER_HEADCROP --threads $THREADS_FILTER \
                | $COMP > 02_filter/${i}.fastq.gz
        } &
        par_wait "$PAR_FILTER"
    done
    par_drain
    # Background pipes cannot trip set -e, so verify every expected output exists and
    # is non-empty; a silent chopper/gzip failure would otherwise surface as an obscure
    # truncated-gzip error deep inside Kraken2 or Flye.
    for i in $(cat samples); do
        [ -s "02_filter/${i}.fastq.gz" ] \
            || { error_log "Chopper produced no output for ${i}. Check the integrity of 01_reads/${i}.fastq.gz."; exit 1; }
    done

    # Read QC (NanoPlot) for both pre- and post-filter FASTQs. These plots are only
    # consumed at the final consolidation step, so we launch them as a bounded
    # background pool here and let them overlap the long Kraken2 + assembly phase,
    # then drain them before annotation. NanoPlot downsamples to 20k reads, so the
    # extra disk pressure during assembly is negligible.
    # (Previously both loops used bare `&` with NO wait and NO bound — a latent race
    # that launched all samples at once and only worked because assembly happened to
    # outlast NanoPlot. par_wait bounds it; the par_drain before annotation fixes it.)
    log "Read QC (NanoPlot, up to ${PAR_QC} samples in parallel, overlaps assembly)..."
    par_reset
    for i in $(cat samples); do
        resume_done "01_reads/QC/${i}/NanoStats.txt" && continue
        MPLBACKEND=Agg NanoPlot --fastq 01_reads/${i}.fastq.gz -o 01_reads/QC/${i} --downsample 20000 --threads 4 --loglength &
        par_wait "$PAR_QC"
    done
    for i in $(cat samples); do
        resume_done "02_filter/QC/${i}/NanoStats.txt" && continue
        MPLBACKEND=Agg NanoPlot --fastq 02_filter/${i}.fastq.gz -o 02_filter/QC/${i} --downsample 20000 --threads 4 --loglength &
        par_wait "$PAR_QC"
    done
else
    log "Skipping preprocessing — using existing reads and QC from previous run."
    if [ ! -s "samples" ]; then
        error_log "'samples' file not found. Re-run without --skip-preprocessing first."
        exit 1
    fi
    # The default end-of-run cleanup prunes 01_reads/ and 02_filter/ (regenerable from
    # fastq_pass/). If a previous complete run pruned them, --skip-preprocessing has
    # nothing to reuse — fail early with a clear pointer instead of an obscure
    # "file not found" deep inside Kraken2/Flye. Regenerate with --just-preprocessing.
    missing_reads=()
    for i in $(cat samples); do
        [ -s "02_filter/${i}.fastq.gz" ] || missing_reads+=("$i")
    done
    if [ ${#missing_reads[@]} -gt 0 ]; then
        error_log "--skip-preprocessing set but filtered reads are missing for: ${missing_reads[*]}"
        error_log "They were likely pruned by the end-of-run cleanup (fastq_pass/ is kept on purpose)."
        error_log "Regenerate them first with --just-preprocessing, then re-run with --skip-preprocessing."
        exit 1
    fi
fi

# Drain the background read-QC pool before stopping, otherwise the NanoPlot jobs
# would be SIGHUP'd on exit with their NanoStats.txt half-written.
[ "$STOP_AFTER" = "preprocessing" ] && { par_drain; log "Done — stopping after preprocessing (--just-preprocessing). Filtered reads in 02_filter/."; exit 0; }

# 2. Taxonomy, assembly, polishing, and assembly QC
conda activate aluminion_assembly

if [ -z "$SKIP_KRAKEN" ]; then
    log "Taxonomy (Kraken2)..."
    # Check whether any sample still needs Kraken2 before the expensive /dev/shm copy
    kraken_needed=false
    for i in $(cat samples); do
        resume_done "04_taxonomies/kraken2/${i}.report" || { kraken_needed=true; break; }
    done
    if [ "$kraken_needed" = true ]; then
        cp ${KRAKEN_DB}/*.k2d /dev/shm/
        for i in $(cat samples); do
            resume_done "04_taxonomies/kraken2/${i}.report" && { log "  [resume] Kraken2: ${i} done, skipping."; continue; }
            kraken2 --memory-mapping --db /dev/shm --minimum-base-quality 10 --minimum-hit-groups 100 --output 04_taxonomies/kraken2/${i}.out --use-names --report 04_taxonomies/kraken2/${i}.report --gzip-compressed 02_filter/${i}.fastq.gz --threads $THREADS_TOTAL
        done
        rm -f /dev/shm/*.k2d
    else
        log "  [resume] All Kraken2 reports found — skipping database copy."
    fi
else
    log "Skipping Kraken2..."
fi

log "Assembly (Flye)..."

# Run Flye under an optional wall-clock limit. A pathological sample (contaminated,
# chimeric, or extreme coverage) can leave Flye spinning inside "Extending reads"
# without ever returning; unwrapped, that hangs the run — and any batch driving it —
# indefinitely, because the failure handler below is only reached when flye exits.
# `timeout` turns that hang into exit code 124, which the handler treats as a failure.
# Extra args (e.g. --meta) are forwarded to flye.
run_flye() {
    local sample="$1"; shift
    # Both flags or neither: --asm-coverage without --genome-size is a Flye usage error.
    local cov_args=()
    if [ -n "$FLYE_ASM_COVERAGE" ] && [ -n "$FLYE_GENOME_SIZE" ]; then
        cov_args=(--genome-size "$FLYE_GENOME_SIZE" --asm-coverage "$FLYE_ASM_COVERAGE")
    fi
    if [ "$FLYE_TIMEOUT" = "0" ]; then
        flye --nano-hq "02_filter/${sample}.fastq.gz" --threads "$THREADS_TOTAL" \
            "${cov_args[@]}" --out-dir "03_assemblies/${sample}" "$@"
    else
        # --foreground lets Flye keep the terminal (so its progress output still reaches
        # the tee'd log); the follow-up SIGKILL after 60s covers a Flye that ignores TERM.
        timeout --foreground --kill-after=60s "$FLYE_TIMEOUT" \
            flye --nano-hq "02_filter/${sample}.fastq.gz" --threads "$THREADS_TOTAL" \
            "${cov_args[@]}" --out-dir "03_assemblies/${sample}" "$@"
    fi
}

# Persistent record of samples Flye could not assemble. Without it, every --resume
# re-queues a known-unassemblable sample and pays the full assembly cost (now up to
# FLYE_TIMEOUT) again before failing in exactly the same way. Samples recorded here are
# skipped on resumed runs; --retry-failed-assembly clears the record to force a retry
# (e.g. after re-sequencing the isolate or raising --flye-timeout).
FAILED_ASSEMBLY_RECORD=".failed_assemblies"
if [ -n "$RETRY_FAILED_ASSEMBLY" ]; then
    [ -f "$FAILED_ASSEMBLY_RECORD" ] && log "Clearing the assembly-failure record (--retry-failed-assembly)."
    rm -f "$FAILED_ASSEMBLY_RECORD"
fi

failed_assembly=()
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/assembly.fasta"; then
        log "  [resume] Flye: ${i} already assembled, skipping."
        continue
    fi
    if [ -n "$RESUME" ] && [ -f "$FAILED_ASSEMBLY_RECORD" ] && grep -qxF "$i" "$FAILED_ASSEMBLY_RECORD"; then
        warn "  [resume] Flye: ${i} previously failed to assemble — skipping (--retry-failed-assembly to retry)."
        failed_assembly+=("$i")
        continue
    fi
    flye_rc=0
    run_flye "$i" || flye_rc=$?
    # 124 (or 137 when the follow-up SIGKILL was needed) means the timeout fired, not
    # that Flye diagnosed a problem — surface that distinction in the log.
    if [ "$flye_rc" -eq 124 ] || [ "$flye_rc" -eq 137 ]; then
        warn "  Flye exceeded the ${FLYE_TIMEOUT} limit on ${i} and was terminated (--flye-timeout)."
        warn "  This usually means a contaminated or unassemblable sample. Inspect 03_assemblies/${i}/flye.log."
    fi
    if [ "$flye_rc" -ne 0 ]; then
        echo ""
        echo "  ┌──────────────────────────────────────────────────────────────────────┐"
        echo "  │  ASSEMBLY FAILED: ${i}                                               |"
        echo "  │  Flye could not assemble this sample (no disjointigs produced).      |"
        echo "  │                                                                      │"
        echo "  │  Options:                                                            │"
        echo "  │    1) Skip sample and continue with the rest                         │"
        echo "  │    2) Retry with --meta (for high-copy or fragmented assemblies)     │"
        echo "  │    3) Stop pipeline for manual inspection                            │"
        echo "  └──────────────────────────────────────────────────────────────────────┘"
        # Only prompt when stdin is an interactive terminal. In batch / piped /
        # nohup runs stdin is NOT a TTY (and would otherwise swallow whatever is
        # piped in — e.g. the batch wrapper's run list), so default to option 1
        # (skip the sample and continue) and record it for the warnings summary.
        if [ -t 0 ]; then
            read -rp "  Choose [1/2/3]: " flye_choice
        else
            flye_choice=1
            warn "  Non-interactive run: defaulting to option 1 (skip ${i} and continue)."
        fi
        case "$flye_choice" in
            1)
                error_log "Skipping sample ${i} — it will be excluded from all downstream steps."
                failed_assembly+=("$i")
                ;;
            2)
                log "Retrying Flye with --meta for sample ${i}..."
                rm -rf 03_assemblies/${i}
                if ! run_flye "$i" --meta; then
                    error_log "Flye --meta also failed for ${i}. Skipping sample."
                    failed_assembly+=("$i")
                else
                    log "Flye --meta succeeded for sample ${i}."
                fi
                ;;
            3)
                error_log "Pipeline stopped by user after assembly failure on sample ${i}."
                exit 1
                ;;
            *)
                error_log "Invalid choice. Stopping pipeline."
                exit 1
                ;;
        esac
    fi
done

if [ ${#failed_assembly[@]} -gt 0 ]; then
    log "Removing ${#failed_assembly[@]} failed sample(s) from pipeline: ${failed_assembly[*]}"
    for s in "${failed_assembly[@]}"; do
        sed -i "/^${s}$/d" samples
        # Remember the failure so a later --resume does not pay the assembly cost again.
        grep -qxF "$s" "$FAILED_ASSEMBLY_RECORD" 2>/dev/null \
            || echo "$s" >> "$FAILED_ASSEMBLY_RECORD"
    done
fi

# ------------------------------------------------------------------------------
# Resolve the dorado polish model ONCE for the whole run.
# ------------------------------------------------------------------------------
# dorado polish auto-resolves (and, if absent, downloads) its model on EVERY
# invocation, so a 24-sample run would fetch the same model 24 times. Every sample
# in a run shares the same basecaller model, so we resolve a single models directory
# up front and point every polish call at it via --models-directory. Resolution order:
#   1. Reuse a models tree already present next to the dorado install (no download).
#   2. Otherwise create a per-run temp dir; dorado downloads into it on the first
#      sample and the remaining samples reuse it. The temp dir is named to match the
#      .temp_dorado_models* pattern pruned by cleanup_run_artifacts.
# Capability is probed from `dorado polish --help` because this flag is not in every
# dorado build; if it is absent we leave the per-sample behaviour untouched (correct,
# just slower) and say so once. The help output is captured first (not piped directly
# into grep) so that pipefail can't misread dorado's own exit code as "flag absent".
polish_models_args=()
dorado_polish_help="$(dorado polish --help 2>&1 || true)"
if printf '%s\n' "$dorado_polish_help" | grep -q -- '--models-directory'; then
    POLISH_MODELS_DIR=""
    dorado_bin="$(readlink -f "$(command -v dorado)")"
    dorado_dir="$(dirname "$dorado_bin")"
    # 1) A model already downloaded next to the dorado install or in the user cache.
    #    Require the directory to be WRITABLE: dorado only downloads a model if it is
    #    missing from the dir, but the resolved model may differ from whatever polish
    #    model already lives there, and writing into a read-only install dir would fail.
    #    A read-only candidate is therefore skipped in favour of the writable temp dir.
    for cand in "${dorado_dir}/models" "$(dirname "$dorado_dir")/models" "$HOME/.cache/dorado/models"; do
        if [ -d "$cand" ] && [ -w "$cand" ] && ls -d "$cand"/*polish* >/dev/null 2>&1; then
            POLISH_MODELS_DIR="$cand"
            log "  Reusing pre-installed dorado polish model directory: ${POLISH_MODELS_DIR}"
            break
        fi
    done
    # 2) Fall back to a per-run temp dir; dorado populates it on the first sample.
    if [ -z "$POLISH_MODELS_DIR" ]; then
        POLISH_MODELS_DIR="$(mktemp -d "${WORKDIR}/.temp_dorado_models.XXXXXX")"
        log "  No pre-installed polish model found — dorado will download it once into ${POLISH_MODELS_DIR}"
    fi
    polish_models_args=(--models-directory "$POLISH_MODELS_DIR")
else
    warn "  This dorado build lacks --models-directory; the polish model is resolved per sample (slower, but correct)."
fi

log "Polishing (dorado polish with @RG injection)..."
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/.polished"; then
        log "  [resume] Polishing: ${i} done, skipping."
        continue
    fi

    # dorado polish requires the basecaller model in the BAM @RG DS field.
    # Dorado embeds it in the FASTQ description — extract it before alignment.
    # `zcat | head -n 1` would trigger SIGPIPE on zcat under set -o pipefail and
    # kill the script silently. Reading via process substitution avoids that:
    # the substituted command's exit status is not part of the foreground pipeline.
    if [ ! -f "02_filter/${i}.fastq.gz" ]; then
        warn "  Missing reads file for ${i} — polishing skipped."
        failed_polish+=("$i")
        continue
    fi
    header=""
    IFS= read -r header < <(zcat 02_filter/${i}.fastq.gz) || true

    if echo "$header" | grep -q 'basecall_model_version_id='; then
        model=$(echo "$header" | awk -F 'basecall_model_version_id=' '{print $2}' | awk '{print $1}')
    else
        # Older Dorado header format without explicit basecall_model_version_id field
        model=$(echo "$header" | grep -o 'dna_[^[:space:]]*' | rev | cut -f3- -d'_' | rev)
    fi

    if [ -z "$model" ]; then
        warn "  Could not detect basecaller model for ${i} — polishing skipped."
        failed_polish+=("$i")
        continue
    fi
    log "  Basecaller model detected for ${i}: ${model}"

    # Stream aligner -> sort -> addreplacerg in a single pipe; the previous version
    # wrote the sorted BAM to disk and re-read it through addreplacerg, doubling I/O
    # per sample. samtools addreplacerg reads BAM from stdin with the `-` argument.
    if echo "$header" | grep -q 'RG:Z:'; then
        # Newer Dorado FASTQ format includes RG:Z: tag.
        # Use dorado aligner --add-fastq-rg to propagate it, then overwrite DS field (-w).
        log "  [polish] FASTQ has RG:Z: — using dorado aligner --add-fastq-rg | sort | addreplacerg"
        rg=$(echo "$header" | awk -F 'RG:Z:' '{print $2}' | awk '{print $1}')
        dorado aligner --add-fastq-rg \
                03_assemblies/${i}/assembly.fasta 02_filter/${i}.fastq.gz \
            | samtools sort -@ $THREADS_TOTAL \
            | samtools addreplacerg -w \
                -r "@RG\tID:${rg}\tDS:basecall_model=${model}" \
                -O bam -o 03_assemblies/${i}/${i}_aligned_reads.bam -
    else
        # Standard Dorado FASTQ (no RG:Z:): dorado aligner adds PN:dorado to @PG,
        # which dorado polish verifies. minimap2 would fail this check.
        log "  [polish] No RG:Z: tag — using dorado aligner | sort | addreplacerg"
        dorado aligner --threads $THREADS_TOTAL \
                03_assemblies/${i}/assembly.fasta 02_filter/${i}.fastq.gz \
            | samtools sort -@ $THREADS_TOTAL \
            | samtools addreplacerg \
                -r "@RG\tID:1\tDS:basecall_model=${model}" \
                -O bam -o 03_assemblies/${i}/${i}_aligned_reads.bam -
    fi
    samtools index -@ $THREADS_TOTAL 03_assemblies/${i}/${i}_aligned_reads.bam

    # --bacteria uses a move-table-free model; GPU auto-detected (remove flag for CPU-only servers).
    # `${polish_models_args[@]+...}` injects --models-directory <dir> only when it was resolved
    # above (empty array safe under set -u), so every sample reuses the model fetched for the run.
    # `${POLISH_BATCHSIZE:+--batchsize $POLISH_BATCHSIZE}` expands to nothing when the user did not
    # set the flag, so dorado falls back to its own default. Override via --polish-batchsize.
    if dorado polish --threads $THREADS_TOTAL --bacteria \
            ${polish_models_args[@]+"${polish_models_args[@]}"} \
            ${POLISH_BATCHSIZE:+--batchsize $POLISH_BATCHSIZE} \
            03_assemblies/${i}/${i}_aligned_reads.bam \
            03_assemblies/${i}/assembly.fasta \
            > 03_assemblies/${i}/polished_assembly.fasta; then
        mv 03_assemblies/${i}/polished_assembly.fasta 03_assemblies/${i}/assembly.fasta
        touch "03_assemblies/${i}/.polished"
    else
        warn "  Polishing failed for ${i}. Assembly kept unpolished."
        failed_polish+=("$i")
        rm -f 03_assemblies/${i}/polished_assembly.fasta
    fi
    rm -f 03_assemblies/${i}/${i}_aligned_reads.bam 03_assemblies/${i}/${i}_aligned_reads.bam.bai
done

log "Deconcatenation & Recircularization..."
> 03_assemblies/deconcat.log
conda activate aluminion_assembly

# Sanity-check the tools deconcat.py needs at runtime. If any are missing the script
# would fail silently for every sample (the warn branch below catches it, but the
# user has no way to know why). Fail fast with a clear message instead.
for dep in blastn makeblastdb mafft em_cons minimap2; do
    if ! command -v "$dep" >/dev/null 2>&1; then
        error_log "deconcat.py dependency '${dep}' not found in aluminion_assembly env. Re-create the env with the current envs/aluminion_assembly.yml."
        exit 1
    fi
done

for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/deconcat/assembly_corr.fasta"; then
        log "  [resume] Deconcat: ${i} done, skipping."
        continue
    fi
    if python3 "$SCRIPTS_PATH/deconcat.py" --fasta_file 03_assemblies/${i}/assembly.fasta \
            --fastq_file 02_filter/${i}.fastq.gz \
            --out_path 03_assemblies/${i}/deconcat >> 03_assemblies/deconcat.log 2>&1 \
        && [ -f 03_assemblies/${i}/deconcat/assembly_corr.fasta ]; then
        cp 03_assemblies/${i}/deconcat/assembly_corr.fasta 03_assemblies/${i}.fasta
    else
        warn "Deconcat failed or produced no output for ${i}. See 03_assemblies/deconcat.log. Using assembly.fasta as-is."
        failed_deconcat+=("$i")
        cp 03_assemblies/${i}/assembly.fasta 03_assemblies/${i}.fasta 2>/dev/null || true
    fi
done
# Reorient circular contigs so the chromosome starts at dnaA, plasmids at repA, etc.
# Replaces the legacy circlator (EOL, libcrypto.so.1.0.0 dependency broken on modern
# distros). The env name is kept for backward compatibility with install.sh.
conda activate aluminion_circlator
[ -n "$RESUME" ] || > 03_assemblies/dnaapler.log
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/.circlator_done"; then
        log "  [resume] Reorientation (dnaapler): ${i} done, skipping."
        continue
    fi
    echo "=== ${i} ===" >> 03_assemblies/dnaapler.log
    # `dnaapler all` inspects each contig and picks the appropriate anchor gene
    # (dnaA/repA/terL) based on contig length and BLAST hits. Output file is
    # ${prefix}_reoriented.fasta inside the output directory.
    if dnaapler all -i 03_assemblies/${i}.fasta -o 03_assemblies/${i}/dnaapler \
                    -p ${i} -t $THREADS_TOTAL --force >>03_assemblies/dnaapler.log 2>&1 \
       && [ -f "03_assemblies/${i}/dnaapler/${i}_reoriented.fasta" ]; then
        cp 03_assemblies/${i}/dnaapler/${i}_reoriented.fasta 03_assemblies/${i}.fasta
        touch "03_assemblies/${i}/.circlator_done"
    else
        warn "dnaapler reorientation failed for ${i}. Assembly kept as-is. See 03_assemblies/dnaapler.log."
        failed_circlator+=("$i")
    fi
done

# QUAST and Bandage live in aluminion_assembly — the previous block left us in
# aluminion_circlator, which does not have them installed.
conda activate aluminion_assembly

log "Assembly QC..."
if resume_done "03_assemblies/quast/transposed_report.tsv"; then
    log "  [resume] QUAST: already done, skipping."
else
    # QUAST 5.x ships the binary as `quast` (no .py suffix); the legacy `quast.py`
    # name is no longer installed in current conda-forge / bioconda builds.
    quast -o 03_assemblies/quast -t $THREADS_TOTAL 03_assemblies/*.fasta
fi
# Bandage uses Qt and tries to open an X display by default — on headless servers
# this aborts with SIGABRT (exit 134) and `set -e` kills the pipeline. Force the
# offscreen Qt backend and wrap the call so a Bandage failure only emits a warning.
[ -n "$RESUME" ] || > 03_assemblies/bandage.log
for i in $(cat samples); do
    resume_done "03_assemblies/${i}.png" && continue
    if ! QT_QPA_PLATFORM=offscreen Bandage image \
            03_assemblies/${i}/assembly_graph.gfa 03_assemblies/${i}.png \
            --lengths --depth --toutline 1.0 >>03_assemblies/bandage.log 2>&1; then
        warn "Bandage image failed for ${i}. See 03_assemblies/bandage.log."
        failed_bandage+=("$i")
    fi
done

# Drain the background read-QC pool (launched during preprocessing) before we either
# stop here or move on to annotation: the consolidation step reads its NanoStats.txt
# outputs, and the later annotation parallel pools must not see leftover QC jobs in
# their concurrency accounting.
par_drain

# Validate NanoPlot pre/post-filter outputs now that the pool has been drained.
# A NanoPlot job that silently failed in the background pool (Chrome wrapper
# missing, choreographer error, OOM) leaves NanoStats.txt absent — the downstream
# `for i in $(cat samples); do grep ... NanoStats.txt | datamash transpose; done`
# loop then emits fewer rows than the `samples` file, and `paste samples
# QC_reads.csv` silently shifts every value column by one, contaminating every
# table and report. Fail fast here with the exact list of missing files so the
# user can re-run with --just-preprocessing once the underlying issue is fixed.
# (Skipped under --skip-preprocessing: the user is responsible for having a
# previous run's QC outputs intact, and the pre-existing reads guard at line ~668
# already vets the filtered FASTQs.)
if [ -z "$SKIP_PREPROCESSING" ]; then
    missing_nanostats=()
    for i in $(cat samples); do
        [ -s "01_reads/QC/${i}/NanoStats.txt" ] || missing_nanostats+=("01_reads/QC/${i}/NanoStats.txt")
        [ -s "02_filter/QC/${i}/NanoStats.txt" ] || missing_nanostats+=("02_filter/QC/${i}/NanoStats.txt")
    done
    if [ ${#missing_nanostats[@]} -gt 0 ]; then
        error_log "NanoPlot output is missing or empty for the following sentinels:"
        for f in "${missing_nanostats[@]}"; do error_log "  - ${f}"; done
        error_log "A NanoPlot job in the parallel QC pool likely failed silently."
        error_log "Check the Chrome wrapper (\${WORKDIR}/.chrome_wrapper) and NanoPlot logs,"
        error_log "then re-run with --just-preprocessing to regenerate the QC outputs."
        exit 1
    fi
fi

[ "$STOP_AFTER" = "assembly" ] && { log "Done — stopping after assembly (--just-assembly). Assemblies in 03_assemblies/."; exit 0; }

# 3. Annotation
conda activate aluminion_annot

log "Annotation (Bakta)..."
for i in $(cat samples); do
    resume_done "08_Anotacion/${i}/${i}.gbff" && { log "  [resume] Bakta: ${i} done, skipping."; continue; }
    bakta --db $BAKTA_DB --output 08_Anotacion/${i} --threads $THREADS_TOTAL 03_assemblies/${i}.fasta --force
done

log "Plasmid Extraction (MOB-Suite Docker, up to ${PAR_MOBSUITE} in parallel)..."
par_reset
for i in $(cat samples); do
    # contig_report.txt AND chromosome.fasta: mob_recon writes contig_report.txt
    # first and chromosome.fasta last (verified: chromosome.fasta is the newest
    # file in 54/54 completed samples), so requiring both means a container killed
    # mid-run is retried instead of skipped. mob_recon already runs with --force,
    # so it overwrites a partial output dir on its own — no cleanup needed here.
    resume_files_done "08_Anotacion/${i}/mob_recon/contig_report.txt" \
                      "08_Anotacion/${i}/mob_recon/chromosome.fasta" \
        && { log "  [resume] MOB-suite: ${i} done, skipping."; continue; }
    # Each call is an independent --rm container writing to its own output dir, so a
    # few can run at once. -n is reduced (THREADS_MOBSUITE) so the pool as a whole
    # does not oversubscribe; mob_recon is BLAST-heavy and still multi-threaded.
    docker run --rm -v $(pwd):/mnt/ --user $(id -u):$(id -g) "$MOBSUITE_IMAGE" mob_recon -i /mnt/03_assemblies/${i}.fasta -o /mnt/08_Anotacion/${i}/mob_recon -c --force -n $THREADS_MOBSUITE &
    par_wait "$PAR_MOBSUITE"
done
par_drain

if [ -z "$SKIP_ABR" ]; then
    log "AMR Screen (Abricate, up to ${PAR_ABRICATE} samples in parallel)..."
    par_reset
    for i in $(cat samples); do
        resume_done "08_Anotacion/${i}/abricate/${i}.tab" && { log "  [resume] Abricate: ${i} done, skipping."; continue; }
        mkdir -p 08_Anotacion/${i}/abricate
        # Single-threaded BLAST, tiny I/O, each writes only its own ${i}.tab → safe to
        # parallelise widely. The --summary below runs only after the pool drains.
        abricate --minid $ABRICATE_MIN_ID --mincov $ABRICATE_MIN_COV 03_assemblies/${i}.fasta > 08_Anotacion/${i}/abricate/${i}.tab &
        par_wait "$PAR_ABRICATE"
    done
    par_drain
    abricate --summary 08_Anotacion/*/abricate/*.tab > 08_Anotacion/AbR.tab
    cp 08_Anotacion/AbR.tab AbR_report.csv

    # Virulence screen against VFDB. Runs on the same assemblies as the AMR
    # screen and uses the same identity/coverage thresholds. parser.py collapses
    # VF_report.csv into a per-sample Virulence_genes column (VF_modif.xlsx),
    # which mge_alerts.py reads to annotate repository matches.
    log "Virulence Screen (Abricate, VFDB, up to ${PAR_ABRICATE} samples in parallel)..."
    par_reset
    for i in $(cat samples); do
        resume_done "08_Anotacion/${i}/abricate_vfdb/${i}.tab" && { log "  [resume] Abricate-VFDB: ${i} done, skipping."; continue; }
        mkdir -p 08_Anotacion/${i}/abricate_vfdb
        abricate --db vfdb --minid $ABRICATE_MIN_ID --mincov $ABRICATE_MIN_COV 03_assemblies/${i}.fasta > 08_Anotacion/${i}/abricate_vfdb/${i}.tab &
        par_wait "$PAR_ABRICATE"
    done
    par_drain
    abricate --summary 08_Anotacion/*/abricate_vfdb/*.tab > 08_Anotacion/VF.tab
    cp 08_Anotacion/VF.tab VF_report.csv
else
    log "Skipping AMR + Virulence Screen (Abricate)..."
fi

# Integrons
if [ -z "$SKIP_INTEGRONS" ]; then
    log "Running Integrons module (Integron_finder)..."
    conda activate aluminion_integron
    for i in $(cat samples); do
        # <sample>.summary is integron_finder's final output (verified present for
        # 118/118 completed samples). The directory itself is created by
        # integron_finder before it does any work (finder.py: os.mkdir(config.outdir)
        # / os.mkdir(config.result_dir) run before the logger is even initialised),
        # so a directory sentinel marks an interrupted sample as done.
        resume_files_done "11_integrons/${i}/Results_Integron_Finder_${i}/${i}.summary" \
            && { log "  [resume] Integron_Finder: ${i} done, skipping."; continue; }
        # integron_finder has no --force and happily reuses a pre-existing outdir,
        # so a partial tree from an interrupted run would be re-parsed as if
        # complete. Clear it before retrying.
        [ -d "11_integrons/${i}" ] && rm -rf "11_integrons/${i}"
        integron_finder 03_assemblies/${i}.fasta --cpu $THREADS_TOTAL --outdir 11_integrons/${i} --func-annot --gbk || true
    done
    conda activate aluminion_annot
    # integron_summary.csv is generated by parser.py (which imports integron_parser
    # and calls run_parsing internally). Direct invocation here would duplicate
    # the work and leave the output in the wrong path.
else
    log "Skipping Integrons module..."
fi

# Plasmid typing (Copla — Docker only)
if [ -z "$SKIP_PLASMIDS" ]; then
    log "Running Plasmid Typing module (Copla, up to ${PAR_COPLA} samples in parallel)..."
    [ -z "$RESUME" ] && > copla.txt
    # Each sample's Copla output goes to its OWN per-sample log file. Concurrent docker
    # containers all redirecting straight into copla.txt would interleave their lines and
    # break copla_parser.py; per-sample logs avoid that. After the pool drains we append
    # the logs back into copla.txt in deterministic (sample) order so the result is
    # reproducible and identical in layout to the old sequential output.
    COPLA_LOGDIR="08_Anotacion/.copla_logs"
    mkdir -p "$COPLA_LOGDIR"
    par_reset
    for j in $(cat samples); do
        # Copla has no single final output file: it emits one set of results per
        # plasmid contig. So the completion test is a COUNT — one
        # *.ptu_prediction.tsv per input plasmid_*.fasta, using the same size
        # filter as the find loop below so the two always agree. A directory
        # sentinel here would skip a sample whose container pool was interrupted
        # after typing only some of its plasmids, and the untyped ones would then
        # read as plasmids with no PTU assignment rather than as missing work.
        if [ -n "$RESUME" ] && [ -d "08_Anotacion/${j}/copla" ]; then
            n_pl=$(find 08_Anotacion/${j}/mob_recon/ -type f -name "plasmid_*.fasta" \
                       -size -600k -size +1k 2>/dev/null | wc -l)
            n_ptu=$(find 08_Anotacion/${j}/copla/ -type f -name "*.ptu_prediction.tsv" \
                       2>/dev/null | wc -l)
            if [ "$n_pl" -eq "$n_ptu" ]; then
                log "  [resume] Copla: ${j} done (${n_ptu}/${n_pl} plasmids), skipping."
                continue
            fi
            warn "Copla: ${j} incomplete (${n_ptu}/${n_pl} plasmids typed). Reprocessing."
        fi
        {
            # MOB-suite names plasmid contigs `plasmid_<CLUSTER>.fasta` (e.g. plasmid_AB949.fasta).
            # The cluster ID lives in field 2 after splitting on `_`; field 1 is the literal
            # word "plasmid". Restricting the glob to `plasmid_*.fasta` also excludes the
            # `chromosome.fasta` MOB-suite emits and the BLAST DB sidecar files (*.ndb etc.).
            find 08_Anotacion/${j}/mob_recon/ -type f -name "plasmid_*.fasta" -size -600k -size +1k | while read -r i; do
                cluster=$(basename "$i" .fasta | cut -d'_' -f2)
                cp "${i}" 05_plasmids/${cluster}_${j}.fasta
                echo "Sample: ${j}" && echo "Contig: ${cluster}" && docker run --rm --cpus "$COPLA_CPUS" -v $(pwd):/tmp "$COPLA_IMAGE" copla /tmp/"${i}" /data/app/databases/Copla_RS84/RS84f_sHSBM.pickle /data/app/databases/Copla_RS84/CoplaDB.fofn /tmp/08_Anotacion/${j}/copla
            done > "${COPLA_LOGDIR}/${j}.txt" 2>&1
        } &
        par_wait "$PAR_COPLA"
    done
    par_drain
    # Stitch per-sample logs into copla.txt in sample order (append, so --resume keeps
    # results from samples skipped above), then drop the scratch logs.
    for j in $(cat samples); do
        [ -f "${COPLA_LOGDIR}/${j}.txt" ] && cat "${COPLA_LOGDIR}/${j}.txt" >> copla.txt
    done
    rm -rf "$COPLA_LOGDIR"
else
    log "Skipping Plasmid module (Copla)..."
fi

# Typing tools: GAMBIT + MLST + Kleborate + ECTyper
if [ -z "$SKIP_TYPING" ]; then
    log "Typing (GAMBIT, MLST, Kleborate, ECTyper)..."
    conda activate aluminion_annot
    # Each typing tool is wrapped non-fatally — a failure in one (e.g. Kleborate hitting
    # a malformed locus call) leaves the others, the parser, and the HTML report intact.
    if resume_done "04_taxonomies/gambit.csv"; then
        log "  [resume] GAMBIT: already done, skipping."
    else
        if ! gambit -d $GAMBIT_DB query -o 04_taxonomies/gambit.csv 03_assemblies/*.fasta; then
            warn "GAMBIT failed. Continuing without genome-level species ID."
            failed_typing+=("GAMBIT")
        fi
    fi
    if resume_done "mlst.csv"; then
        log "  [resume] MLST: already done, skipping."
    else
        if ! mlst 03_assemblies/*.fasta -q > mlst.csv; then
            warn "MLST failed. Continuing without sequence typing."
            failed_typing+=("MLST")
        fi
    fi
    conda activate aluminion_kleborate
    cp 03_assemblies/*.fasta 04_taxonomies/gtdb/
    if resume_done "04_taxonomies/kleborate/enterobacterales__species_output.txt"; then
        log "  [resume] Kleborate: already done, skipping."
    else
        if kleborate -a 03_assemblies/*.fasta -o 04_taxonomies/kleborate -m enterobacterales__species,klebsiella_pneumo_complex__amr,klebsiella_pneumo_complex__kaptive,klebsiella_pneumo_complex__mlst,escherichia__mlst_achtman,klebsiella_pneumo_complex__resistance_score,klebsiella_pneumo_complex__resistance_gene_count,klebsiella__ybst,klebsiella__cbst,klebsiella__abst,klebsiella__smst,klebsiella__rmst,klebsiella__rmpa2,klebsiella_pneumo_complex__virulence_score; then
            cp 04_taxonomies/kleborate/enterobacterales__species_output.txt kleborate.tsv || true
        else
            warn "Kleborate failed. Continuing without Enterobacterales typing."
            failed_typing+=("Kleborate")
        fi
    fi
    if resume_done "04_taxonomies/ectyper/output.tsv"; then
        log "  [resume] ECTyper: already done, skipping."
    else
        if ! ectyper -i 04_taxonomies/gtdb -o 04_taxonomies/ectyper; then
            warn "ECTyper failed. Continuing without E. coli serotyping."
            failed_typing+=("ECTyper")
        fi
    fi
    conda activate aluminion_annot
else
    log "Skipping Typing (GAMBIT, MLST, Kleborate, ECTyper)..."
fi


# 5. Phastest (Docker)
#
# Phastest completion sentinel: `success.txt`, NOT the directory.
# ---------------------------------------------------------------
# The output directory is created by THIS script before the container runs, so
# `resume_done <dir>` is true the instant the sample starts. A sample interrupted
# mid-flight therefore looks complete on the next --resume and is skipped with an
# empty (or partial) directory — its prophages silently become "none found",
# indistinguishable from a genuine negative. Observed on ENTHERE_2026_JUL_07:
# SCT-HURS-13 was skipped with 0 files after a Ctrl+C. Phastest writes success.txt
# only after the run completes, so that is the sentinel we test. A directory
# without success.txt is stale residue and is cleared before retrying.
phastest_done() { [ -n "$RESUME" ] && [ -f "09_phages/phastest_deep/${1}/success.txt" ]; }

# Reset the Phastest SLURM cluster before a sample.
# -------------------------------------------------
# The phastest-docker stack runs 8 persistent compute nodes (c1..c8, slurmd) but
# the CONTROLLER (slurmctld) lives in the ephemeral `run --rm` container aluminion
# launches per sample — docker-compose.yml comments the standalone slurmctld
# service out and gives the ephemeral service `hostname: slurmctld`. So the
# scheduler's brain is born and dies with every sample while the nodes persist,
# and slurm.conf sets ReturnToService=0, meaning a node the dying controller
# marked down never comes back on its own.
#
# Consequence, observed on ENTHERE_2026_JUL_07 after a Ctrl+C, and again on
# ENTHERE_2026_JUN_25 (every sample from the second one onward failed both
# attempts — 9/9, 0% recovered by a retry, once the cluster degraded mid-run):
# BLAST is dispatched as an `sbatch --array=1-N --wait` job, and array pieces
# silently never get scheduled. The remaining pieces finish in minutes, then
# `--wait` blocks until phastest.pl's internal phage_finder_tolerate_time
# (180 min) expires and the sample dies with no results. The pieces themselves
# are ordinary protein and the phage DB is intact — the work is fine, the
# scheduler lost the jobs.
#
# `docker compose restart` on the node containers only restarts the process
# inside the SAME container filesystem layer — it does not clear whatever stuck
# state (munge sockets, slurmd lock/PID files, orphaned job registrations) lives
# in that writable layer, and empirically it never recovered dispatch once a run
# degraded (0/9 retries recovered, across every run logged so far).
# `docker compose down --remove-orphans` destroys and recreates every container
# from scratch — the named volumes (etc_slurm, slurm_jobdir, the slurmdbd
# database) persist, but each node's writable layer is wiped. This is the reset
# a manually-run version of this pipeline used successfully before this module
# existed. It costs more per sample than a plain restart (a full cluster
# bring-up, not 8 process restarts), but only a full teardown has actually been
# observed to clear a stuck cluster, so it now runs before every attempt rather
# than once per run. Non-fatal: if the reset fails we still try the sample.
phastest_reset_cluster() {
    # ${VAR:-} and not $VAR: this script runs under `set -euo pipefail`, so
    # dereferencing an unset variable aborts with "unbound variable". Every
    # optional/env-provided knob must carry the :- default.
    [ -n "${PHASTEST_NO_RESET:-}" ] && return 0
    log "  Phastest: tearing down cluster (docker compose down --remove-orphans)..."
    if ! docker compose -f "${PHASTEST_DIR}/docker-compose.yml" down --remove-orphans >/dev/null 2>&1; then
        warn "Phastest: could not tear down cluster. Continuing (jobs may stall)."
        return 1
    fi
    # `docker compose run` below brings its depends_on services (slurmdbd,
    # c1..c8) back up automatically, but slurmd needs a moment after joining to
    # register with the new controller before sbatch dispatch is reliable.
    sleep "${ALUMINION_PHASTEST_RESET_WAIT:-20}"
    return 0
}

if [ -z "$SKIP_PHAGES" ]; then
    log "Running Phages module (Phastest)..."
    host_uid=$(id -u); host_gid=$(id -g)
    for i in $(cat samples); do
        if phastest_done "$i"; then
            log "  [resume] Phastest: ${i} done, skipping."
            continue
        fi
        # No success.txt but a directory present = interrupted/timed-out attempt.
        # Clear it so the retry starts clean and the copy below can't mix runs.
        if [ -d "09_phages/phastest_deep/${i}" ] && \
           [ -n "$(find "09_phages/phastest_deep/${i}" -mindepth 1 -print -quit 2>/dev/null)" ]; then
            warn "Phastest: ${i} has no success.txt (interrupted or timed out). Retrying from scratch."
            rm -rf "09_phages/phastest_deep/${i}"
        fi
        mkdir -p 09_phages/phastest_deep/"$i"/

        # Phastest processes the input FASTA in-place inside its container (which runs
        # as root) and stamps the file with root:root ownership. If a prior run aborted
        # before line `rm -rf .../phastest_inputs/$i.fasta` (e.g. a downstream failure),
        # the leftover input file persists as root:root mode 644, and a plain `cp` from
        # the host user can't truncate-overwrite it → "Permiso denegado". The dir itself
        # is host-user-owned, so `rm -f` works (only needs dir write perm). Clear any
        # stale residue first, then copy. `cp -f` adds belt-and-braces unlink-then-create.
        rm -f "${PHASTEST_DIR}/phastest_inputs/${i}.fasta"
        if ! cp -f 03_assemblies/"$i".fasta "${PHASTEST_DIR}/phastest_inputs/"; then
            warn "Phastest: could not stage ${i}.fasta in ${PHASTEST_DIR}/phastest_inputs/. Skipping."
            failed_phages+=("$i")
            continue
        fi

        # Phastest must run as root inside the container — its perl scripts live in
        # /root/phastest-app/scripts/ with 700 perms. Passing --user <host_uid:gid>
        # makes them unreadable, which silently breaks prophage detection (fixed in
        # b6d1260). `--phage-only` on its own (without --user) is safe — it limits
        # Phastest to the phage-detection steps this pipeline actually consumes,
        # trimming the per-sample SLURM array workload, and matches the manually-run
        # method that worked reliably before this module existed.
        #
        # Side effect: Phastest creates JOBS/$i as root AND mutates the input file
        # under phastest_inputs/ to root ownership. Wrap the phastest call in `bash -c`
        # so the same container (still root) chowns BOTH trees back to the host user
        # before exiting; otherwise the next sample's `cp` fails with EACCES as above.
        # The inputs bind-mount target inside the container is `/phastest-app/inputs`
        # (phastest-docker default; verify with `docker compose config`). Phastest's
        # exit code is preserved via $rc.
        # Two attempts, each behind its own full cluster teardown (see
        # phastest_reset_cluster above) — a sample that dies at the 180 min tolerate
        # time produced nothing, so retrying costs time but not results; without the
        # retry a single scheduler hiccup discards the sample's prophage calls outright.
        # Same residue hazard as the input FASTA above, and for the same reason: a
        # run killed between the container exiting and the `rm -rf` below leaves
        # JOBS/$i behind, root- or nobody-owned. Phastest would then start on top of
        # a foreign tree and the `cp -r` afterwards would mix two attempts' outputs
        # into one sample. Observed after the Ctrl+C on ENTHERE_2026_JUL_07:
        # JOBS/SCT-HURS-13 (usuario) and JOBS/SCT-HURS-44 (nobody:nogroup) survived.
        # JOBS/ itself is host-user-owned, so `rm -rf` on a child works regardless of
        # who owns the child (only the parent's write bit matters).
        rm -rf "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i"

        phastest_ok=""
        for attempt in 1 2; do
            log "  Phastest: ${i} attempt ${attempt}/2 (full cluster teardown first)..."
            phastest_reset_cluster || true
            if docker compose -f "${PHASTEST_DIR}/docker-compose.yml" run --rm \
                    --entrypoint /bin/bash phastest \
                    -c "phastest -i fasta -m deep -s '$i'.fasta --phage-only --yes; rc=\$?; \
                        chown -R ${host_uid}:${host_gid} /phastest-app/JOBS/'$i' /phastest-app/inputs 2>/dev/null; \
                        exit \$rc"; then
                # Exit 0 is not enough: phastest.pl returns 0 after phage_finder times
                # out. success.txt is the only trustworthy signal of a real result.
                if [ -f "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i/success.txt" ]; then
                    phastest_ok="yes"
                    break
                fi
                warn "Phastest: ${i} exited 0 but wrote no success.txt (phage_finder timeout)."
            else
                warn "Phastest container exited non-zero for ${i}."
            fi
            # Clear the failed attempt's tree so attempt 2 (or the next run) starts clean.
            rm -rf "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i"
        done
        if [ -z "$phastest_ok" ]; then
            warn "Phastest failed for ${i} after 2 attempts. Continuing without its prophages."
            failed_phages+=("$i")
            # Fall through to cleanup so leftovers don't poison the next sample.
        fi

        cp -r "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i/"* 09_phages/phastest_deep/"$i"/ 2>/dev/null || true
        rm -rf "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i" "${PHASTEST_DIR}/phastest_inputs/$i.fasta"
    done
    conda activate aluminion_annot
    # phage_summary.csv is generated by parser.py (which imports phage_parser
    # and calls run_parsing internally). Direct invocation here would duplicate
    # the work and leave the output in the wrong path.
else
    log "Skipping Phages module..."
fi


# 6. Final Tables, IS, and consolidation (always aluminion_annot)
conda activate aluminion_annot
log "IS parsing and Final Tables..."
# Always rebuild IS.tsv from scratch so resumed runs include all samples — the
# per-sample IS_chr_out.tsv files are preserved by their own resume sentinel.
echo -e "sample\tmax\tIS_name\tTotal_IS" > IS.tsv
for i in $(cat samples); do
    if [ -f "08_Anotacion/${i}/mob_recon/chromosome.fasta" ]; then
        if ! resume_done "08_Anotacion/${i}/IS_chr_out.tsv"; then
            sed -i 's/>contig/>Chr/g' "08_Anotacion/${i}/mob_recon/chromosome.fasta"
            makeblastdb -in "08_Anotacion/${i}/mob_recon/chromosome.fasta" -dbtype nucl
            blastn -db "08_Anotacion/${i}/mob_recon/chromosome.fasta" -query "$ISFINDER_DB" -outfmt "6 qseqid sseqid sstart send pident mismatch evalue" | sort -k 3 > 08_Anotacion/${i}/IS_chr.tsv
            python3 "$SCRIPTS_PATH/IS_parser.py" -i 08_Anotacion/${i}
        else
            log "  [resume] IS search: ${i} done, skipping."
        fi
        cat 08_Anotacion/${i}/IS_chr_out.tsv | cut -f 2 | sort | uniq -c | sort -r | awk '{print $1"\t"$2}' > 08_Anotacion/${i}/N_IS_${i}.tsv
        # head/tail/wc on an empty file return success with empty output, so the
        # original `|| echo ...` fallback never fired. Guard explicitly with -s.
        if [ -s "08_Anotacion/${i}/N_IS_${i}.tsv" ]; then
            MAX_IS=$(head -n 1 "08_Anotacion/${i}/N_IS_${i}.tsv")
        else
            MAX_IS=$'0\tNone'
        fi
        if [ -s "08_Anotacion/${i}/IS_chr_out.tsv" ]; then
            TOTAL_IS=$(tail -n +2 "08_Anotacion/${i}/IS_chr_out.tsv" | wc -l)
        else
            TOTAL_IS=0
        fi
        echo -e "${i}\t${MAX_IS}\t${TOTAL_IS}" >> IS.tsv
    fi
done

# Text parsing (Awk, Sed, Python)
for i in $(cat samples); do grep 'Median read length\|Median read quality\|Number of reads\|Total bases\|1:' 01_reads/QC/${i}/NanoStats.txt | cut -d ':' -f 2 | cut -d '(' -f 1 | column -t | datamash transpose; done > 01_reads/QC_reads.csv
paste samples 01_reads/QC_reads.csv > 01_reads/QC_reads_pre.csv
sed -i '1 i\Sample\tMedian length\tMedian quality\tTotal reads\tTotal bases\tMaxQ\tLongest read' 01_reads/QC_reads_pre.csv
cp 01_reads/QC_reads_pre.csv QC_reads_pre.csv 

for i in $(cat samples); do grep 'Median read length\|Median read quality\|Number of reads\|Total bases\|1:' 02_filter/QC/${i}/NanoStats.txt | cut -d ':' -f 2 | cut -d '(' -f 1 | column -t | datamash transpose; done > 02_filter/QC_reads.csv
paste samples 02_filter/QC_reads.csv > 02_filter/QC_reads_post.csv
sed -i '1 i\Sample\tMedian length\tMedian quality\tTotal reads\tTotal bases\tMaxQ\tLongest read' 02_filter/QC_reads_post.csv
cp 02_filter/QC_reads_post.csv QC_reads_post.csv 

paste QC_reads_pre.csv QC_reads_post.csv > QC_reads.csv; rm QC_reads_pre.csv QC_reads_post.csv 

> 04_taxonomies/kraken2/genus.csv
> 04_taxonomies/kraken2/species.csv
for i in $(cat samples); do
    # Build a clean TSV row: <sample>\t<percent>\t<taxon_name>. The previous
    # awk used commas (which insert OFS=" ") and trailing empty fields ($3, $4)
    # that introduced stray spaces in the Sample/Genus/Species columns and
    # broke the merge against list_seq.tsv downstream. Set OFS=tab and
    # concatenate the taxon name words with single spaces by hand.
    awk '($1 >= 20 && $4 == "G")' 04_taxonomies/kraken2/${i}.report | cut -f 1,6 | tr -s '  ' \
        | awk -v OFS='\t' '{n=$2; for(j=3;j<=NF;j++) n=n" "$j; print i, $1, n}' i="${i}" \
        >> 04_taxonomies/kraken2/genus.csv || true
    awk '($1 >= 4  && $4 == "S")' 04_taxonomies/kraken2/${i}.report | cut -f 1,6 | tr -s '  ' \
        | awk -v OFS='\t' '{n=$2; for(j=3;j<=NF;j++) n=n" "$j; print i, $1, n}' i="${i}" \
        >> 04_taxonomies/kraken2/species.csv || true
done
awk -F"\t" 'NR==FNR{a[$1]=$0;next} ($1 in a){b=$1;$1="";print a[b] $0}' OFS="\t" 04_taxonomies/kraken2/genus.csv 04_taxonomies/kraken2/species.csv > 04_taxonomies/kraken_report.csv || true
sed -i '1 i\Sample\tReads(%)\tGenus\tReads(%)\tSpecies' 04_taxonomies/kraken_report.csv || true
sed 's/\t[[:blank:]]*/\t/g' 04_taxonomies/kraken_report.csv > kraken.csv || true

cut 03_assemblies/quast/transposed_report.tsv -f 1,14-17,26 > QC_assembly.csv
sed -i 's/Assembly/Samples/' QC_assembly.csv

log "Executing final consolidation in Python (Orchestrator)..."
python3 "$SCRIPTS_PATH/parser.py" -i . $SKIP_PHAGES $SKIP_INTEGRONS $SKIP_PLASMIDS $SKIP_TYPING $SKIP_KRAKEN $SKIP_ABR

log "Generating Interactive HTML Report..."
python3 "$SCRIPTS_PATH/aluminion_reporter.py" "$PWD"

log "Updating historical databases (data_seq.tsv / data_analysis.tsv)..."
# The cumulative DB lives in the batch parent ($BASE_DIR) so it summarizes every
# run; a per-run snapshot is always written to the run folder. --unique-run keeps
# the run isolated: it skips --db-dir so the shared cumulative DB is left untouched.
DB_DIR_ARG=""
[ -z "$UNIQUE_RUN" ] && DB_DIR_ARG="--db-dir $BASE_DIR"
python3 "$SCRIPTS_PATH/lab_db_updater.py" --input_path . $DB_DIR_ARG $INIT_DB

# Cross-run MGE alerts: ingest this run's plasmids/integrons into the cumulative
# repository and emit alerts.tsv + Alerts_Report.html when a recurrent or
# priority-gene-carrying element is detected. Runs after lab_db_updater.py
# because mge_alerts.py reads the freshly written data_analysis.tsv.
if [ -z "$NO_ALERTS" ]; then
    if [ -n "$INIT_REPO" ] || [ ! -f "$REPO/index_plasmids.tsv" ]; then
        log "Initializing MGE repository at $REPO"
        conda activate aluminion_annot
        python3 -c "import sys; sys.path.insert(0, '$SCRIPTS_PATH'); from mge_repository import Repository; Repository.init('$REPO')"
    fi
    if [ -f "$REPO/index_plasmids.tsv" ]; then
        log "Running cross-run MGE alerts (repository: $REPO)..."
        conda activate aluminion_annot
        python3 "$SCRIPTS_PATH/mge_alerts.py" \
            --run-dir "$PWD" \
            --repo "$REPO" \
            --run-name "$RUN_NAME" \
            $ALERT_NEW_PRIORITY \
        || warn "MGE alerts step failed (non-fatal). See log for details."
    else
        warn "MGE repository was not created at $REPO. Alerts step skipped."
    fi
else
    log "Skipping cross-run MGE alerts (--no-alerts)."
fi

# Print a consolidated warning summary for all non-fatal failures
if [ ${#failed_polish[@]} -gt 0 ] || [ ${#failed_deconcat[@]} -gt 0 ] || [ ${#failed_circlator[@]} -gt 0 ] \
   || [ ${#failed_bandage[@]} -gt 0 ] || [ ${#failed_typing[@]} -gt 0 ] || [ ${#failed_phages[@]} -gt 0 ]; then
    echo ""
    warn "========================================================================"
    warn "Pipeline finished with warnings — the run completed but the following"
    warn "optional steps failed (assemblies and core annotations are still valid):"
    [ ${#failed_polish[@]}    -gt 0 ] && warn "  Unpolished  (dorado polish failed): ${failed_polish[*]}"
    [ ${#failed_deconcat[@]}  -gt 0 ] && warn "  Deconcatenation failed            : ${failed_deconcat[*]}"
    [ ${#failed_circlator[@]} -gt 0 ] && warn "  Not recircularized (circlator)    : ${failed_circlator[*]}"
    [ ${#failed_bandage[@]}   -gt 0 ] && warn "  No assembly graph image (Bandage) : ${failed_bandage[*]}"
    [ ${#failed_typing[@]}    -gt 0 ] && warn "  Typing tools failed               : ${failed_typing[*]}"
    [ ${#failed_phages[@]}    -gt 0 ] && warn "  Phastest failed (no prophages)    : ${failed_phages[*]}"
    warn "========================================================================"
    echo ""
fi

# Prune disposable intermediates now that every downstream step has consumed them.
# Skipped under --keep-everything, and also when any optional step failed: an
# imperfect run keeps all intermediates so the user can inspect what went wrong.
had_warnings=$(( ${#failed_polish[@]} + ${#failed_deconcat[@]} + ${#failed_circlator[@]} \
               + ${#failed_bandage[@]} + ${#failed_typing[@]} + ${#failed_phages[@]} ))
if [ -n "$KEEP_EVERYTHING" ]; then
    log "Keeping all intermediate files (--keep-everything)."
elif [ "$had_warnings" -gt 0 ]; then
    warn "Run finished with warnings — keeping all intermediate files for inspection."
    warn "Re-run with the issues resolved, or pass --keep-everything, to control pruning."
else
    cleanup_run_artifacts
fi

if [ -n "$UNIQUE_RUN" ]; then
    log "Pipeline successfully finished in --unique-run mode (no repository interaction). Aluminion out."
else
    log "Pipeline successfully finished. Aluminion out."
fi