#!/bin/bash

# ==============================================================================
# Aluminion - Bacterial WGS Pipeline
# ==============================================================================

# Detectar la ruta donde se encuentra este script aluminion.sh
SCRIPT_DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )"

# Definir la ruta de los scripts auxiliares (por defecto la subcarpeta scripts/)
SCRIPTS_PATH="${ALUMINION_SCRIPTS:-$SCRIPT_DIR/scripts}"


set -euo pipefail

# ==============================================================================
# DEFAULT PARAMETERS
# ==============================================================================
THREADS_TOTAL=30
RUN_NAME=""
BASE_DIR="/home/usuario/Seqs/Servicio"
SEQ_LIST_INPUT=""
DB_DIR="/home/usuario/Databases"
PHASTEST_DIR="${ALUMINION_PHASTEST_DIR:-$HOME/Programs/phastest-docker}"
MINKNOW_DIR="${ALUMINION_MINKNOW_DIR:-/var/lib/minknow/data}"

# Docker image versions — update here after testing a new release
MOBSUITE_IMAGE="kbessonov/mob_suite:3.0.3"
COPLA_IMAGE="rpalcab/copla:1.0"

show_help() {
    cat << EOF

Aluminion: Automated pipeline for bacterial genomes (Oxford Nanopore)

Usage: aluminion -r <run_name> [options]

Mandatory options:
  -r, --run       Name of the run folder generated by MinKNOW.

Additional options:
  -b, --db-dir    Path to the main Databases directory.
                  (Default: /home/usuario/Databases)
  -t, --threads   Number of threads/cores to use. (Default: 30)
  -l, --list      Path to the list_seq.tsv file.
  -d, --dir       Base working directory to save the analysis.
  -p, --phastest-dir  Path to the local Phastest docker-compose folder.
                  (Default: \$ALUMINION_PHASTEST_DIR or ~/Programs/phastest-docker)
  -m, --minknow-dir   Path to the MinKNOW data root directory.
                  (Default: \$ALUMINION_MINKNOW_DIR or /var/lib/minknow/data)
  --init-db       First run: create data_seq.tsv and data_analysis.tsv from scratch.
                  Also triggered automatically if those files do not exist.
  --resume        Resume a previously interrupted run. Each step checks whether
                  its output already exists and skips it if so. Use after any
                  mid-run failure to avoid repeating completed work.
  --skip-preprocessing  Skip read QC and filtering (NanoPlot + Chopper). Requires a
                  previous run to have completed this step (01_reads/, 02_filter/,
                  and samples file must exist).
  --skip-kraken   Skip Kraken2 read-level classification.
  --skip-abr      Skip Abricate AMR resistance gene screen.
  --skip-typing   Skip all typing tools: GAMBIT, MLST, Kleborate, ECTyper.
  --skip-integrons  Skip Integron_Finder and integron parsing.
  --skip-plasmids   Skip Copla plasmid typing (MOB-suite always runs).
  --skip-phages     Skip Phastest prophage detection.

Early-stop flags (run only up to the named stage, then exit):
  --just-preprocessing  Stop after read QC and filtering. Output: filtered FASTQ in 02_filter/.
  --just-assembly       Stop after assembly, polishing, and QUAST. Output: FASTA in 03_assemblies/.
  -h, --help      Show this help message and exit.

Example:
  aluminion -r BAC_2025_NOV_25 -b /mnt/data/Databases -t 60

EOF
}

log()       { echo -e "\n\033[1;32m[$(date +'%Y-%m-%d %H:%M:%S')] $1\033[0m"; }
error_log() { echo -e "\n\033[1;31m[ERROR] $1\033[0m"; }
warn()      { echo -e "\033[1;33m[WARNING] $1\033[0m"; }
# Returns true if --resume is active and the sentinel file or directory already exists
resume_done() { [ -n "$RESUME" ] && { [ -f "$1" ] || [ -d "$1" ]; }; }

# Tracks samples that completed assembly but failed optional refinement steps
failed_polish=()
failed_deconcat=()
failed_circlator=()

# ==============================================================================
# COMMAND LINE ARGUMENT PARSING
# ==============================================================================

RESUME=""
STOP_AFTER=""
SKIP_PREPROCESSING=""
SKIP_PHAGES=""
SKIP_INTEGRONS=""
SKIP_PLASMIDS=""
SKIP_TYPING=""
SKIP_KRAKEN=""
SKIP_ABR=""
INIT_DB=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -r|--run) RUN_NAME="$2"; shift ;;
        -b|--db-dir) DB_DIR="$2"; shift ;;
        -t|--threads) THREADS_TOTAL="$2"; shift ;;
        -l|--list) SEQ_LIST_INPUT="$2"; shift ;;
        -d|--dir) BASE_DIR="$2"; shift ;;
        -p|--phastest-dir) PHASTEST_DIR="$2"; shift ;;
        -m|--minknow-dir) MINKNOW_DIR="$2"; shift ;;
        --resume) RESUME=true ;;
        # Flags for skipping steps
        --skip-preprocessing) SKIP_PREPROCESSING=true ;;
        --skip-phages) SKIP_PHAGES="--skip-phages" ;;
        --skip-integrons) SKIP_INTEGRONS="--skip-integrons" ;;
        --skip-plasmids) SKIP_PLASMIDS="--skip-plasmids" ;;
        --skip-typing) SKIP_TYPING="--skip-typing" ;;
        --skip-kraken) SKIP_KRAKEN="--skip-kraken" ;;
        --skip-abr) SKIP_ABR="--skip-abr" ;;
        --init-db) INIT_DB="--init" ;;
        # Early-stop flags
        --just-preprocessing) STOP_AFTER="preprocessing" ;;
        --just-assembly) STOP_AFTER="assembly" ;;
        -h|--help) show_help; exit 0 ;;
        *) error_log "Unknown parameter: $1"; show_help; exit 1 ;;
    esac
    shift
done

if [ -z "$RUN_NAME" ]; then
    error_log "The -r / --run parameter is mandatory."
    show_help; exit 1
fi

# Resolve relative paths before any cd changes the working directory
[ -n "$SEQ_LIST_INPUT" ] && SEQ_LIST_INPUT="$(readlink -f "$SEQ_LIST_INPUT")"
[ -n "$BASE_DIR"       ] && BASE_DIR="$(readlink -f "$BASE_DIR")"

if [ ! -d "$DB_DIR" ]; then
    error_log "Database directory not found: $DB_DIR. Please check the -b parameter."
    exit 1
fi

# ==============================================================================
# DEPENDENCY CHECKS
# ==============================================================================
# samtools, datamash, blast, etc. are checked at runtime inside their conda envs
for dep in docker dorado; do
    command -v "$dep" >/dev/null 2>&1 || { error_log "Required tool '$dep' not found in PATH. Install it before running the pipeline."; exit 1; }
done

if ! command -v docker >/dev/null 2>&1; then
    error_log "Docker not found. Required for MOB-suite, Copla, and Phastest. Install Docker and ensure the daemon is running."
    exit 1
fi

WORKDIR="${BASE_DIR}/${RUN_NAME}"

# Databases routing
KRAKEN_DB="${DB_DIR}/Kraken"
GAMBIT_DB="${DB_DIR}/gambit"
BAKTA_DB="${DB_DIR}/bakta/db"
MEGARES_DB="${DB_DIR}/megares/sequences"
ISFINDER_DB="${DB_DIR}/ISfinder/ISfinder-nucl.fasta"

# Conda Initialization
if [ -f "$HOME/mambaforge/etc/profile.d/conda.sh" ]; then
    source "$HOME/mambaforge/etc/profile.d/conda.sh"
elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
else
    error_log "Could not find conda.sh initialization script."
    exit 1
fi

# ==============================================================================
# DIRECTORY AND DATA PREPARATION
# ==============================================================================
mkdir -p "$WORKDIR"
LOG_FILE="${WORKDIR}/aluminion_$(date +'%Y%m%d_%H%M%S').log"
exec > >(tee -a "$LOG_FILE") 2>&1

log "Starting Aluminion for run: $RUN_NAME"
log "Log file: $LOG_FILE"
cd "$WORKDIR"

# Copy MinKNOW metadata files (small, always needed)
cp "${MINKNOW_DIR}/${RUN_NAME}/no_sample_id/"*/final_summary_*.txt . 2>/dev/null || true
cp "${MINKNOW_DIR}/${RUN_NAME}/no_sample_id/"*/report_*.json      . 2>/dev/null || true

# Ensure list_seq.tsv is in place before reading barcodes from it
if [ -n "$SEQ_LIST_INPUT" ] && [ -f "$SEQ_LIST_INPUT" ]; then
    cp "$SEQ_LIST_INPUT" "list_seq.tsv"
fi

if [ ! -f "list_seq.tsv" ]; then
    echo -e "Lab_id\tStrain\tID\tBarcode\tDNA_conc\tis_repeated" > list_seq.tsv
    error_log "Empty 'list_seq.tsv' created. Fill it out and re-run."
    exit 1
fi

# Copy only the barcode subfolders referenced in list_seq.tsv (col 4 = Barcode)
mkdir -p fastq_pass
FASTQ_SRC=$(ls -d "${MINKNOW_DIR}/${RUN_NAME}/no_sample_id/"*/fastq_pass 2>/dev/null | head -n1)
if [ -n "$FASTQ_SRC" ]; then
    tail -n +2 list_seq.tsv \
        | awk -F'\t' '{print $4}' \
        | grep -Ev '^[[:space:]]*$|^[xX]$' \
        | sort -u \
        | while read -r bc; do
            padded=$(printf "%02d" "$bc")
            src="${FASTQ_SRC}/barcode${padded}"
            if [ -d "$src" ]; then
                cp -r "$src" fastq_pass/
            else
                log "Warning: barcode${padded} not found in MinKNOW fastq_pass — skipping."
            fi
        done
else
    log "Warning: MinKNOW fastq_pass directory not found. Continuing without copying reads."
fi

mkdir -p 01_reads/QC 02_filter/QC 03_assemblies/quast 04_taxonomies/{kraken2,gtdb} 05_plasmids 08_Anotacion 09_phages 10_ices 11_integrons ../repositorio/{01_reads,03_assemblies,05_plasmids,08_Anotacion,09_phages,10_ices,11_integrons}

# ==============================================================================
# PIPELINE EXECUTION
# ==============================================================================

# 1. Read preparation and QC/filtering
if [ -z "$SKIP_PREPROCESSING" ]; then
    echo -e "ID\tR1\tR2\tLongFastQ\tFast5\tGenomeSize\tFasta" > samplesheet.tsv

    tail -n +2 list_seq.tsv | while IFS=$'\t' read -r cult cep id bc c rep; do
        [ -z "$id" ] && continue
        if resume_done "01_reads/${id}.fastq.gz"; then
            log "  [resume] Read concat: ${id} already done, skipping."
        elif [ -z "$rep" ]; then
            cat fastq_pass/barcode${bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
            cp 01_reads/${id}.fastq.gz ../repositorio/01_reads/${id}.fastq.gz
        else
            cat ../repositorio/01_reads/${id}.fastq.gz fastq_pass/barcode${bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
            cp 01_reads/${id}.fastq.gz ../repositorio/01_reads/${id}.fastq.gz
        fi
        echo -e "${id}\t\t\t$PWD/01_reads/${id}.fastq.gz\t\t" >> samplesheet.tsv
    done

    cut -f3 list_seq.tsv | tail -n+2 > ../repositorio/samples
    find 01_reads -type f -name "*.fastq.gz" -size +135M -exec basename {} .fastq.gz \; | sort | uniq > samples

    if [ ! -s samples ]; then
        error_log "No samples passed the 135MB filter."
        exit 1
    fi

    conda activate aluminion_reads

    # Chrome (used by NanoPlot's plot renderer) requires --no-sandbox on headless Linux servers.
    # Use glob to find the bundled binary — more reliable than calling Python after conda activate.
    CHROME_REAL=$(ls "$HOME/mambaforge/envs/aluminion_reads/lib/python"*/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome 2>/dev/null | head -1)
    if [ -n "$CHROME_REAL" ] && [ -x "$CHROME_REAL" ]; then
        CHROME_WRAPPER="${WORKDIR}/.chrome_wrapper"
        printf '#!/bin/bash\nexec "%s" --no-sandbox --disable-gpu --disable-dev-shm-usage "$@"\n' "$CHROME_REAL" > "$CHROME_WRAPPER"
        chmod +x "$CHROME_WRAPPER"
        export BROWSER_PATH="$CHROME_WRAPPER"
    fi

    log "Pre-filtering QC..."
    for i in $(cat samples); do
        resume_done "01_reads/QC/${i}/NanoStats.txt" && continue
        MPLBACKEND=Agg NanoPlot --fastq 01_reads/${i}.fastq.gz -o 01_reads/QC/${i} --downsample 20000 --threads 4 --loglength &
    done

    log "Filtering (Chopper)..."
    for i in $(cat samples); do
        resume_done "02_filter/${i}.fastq.gz" && { log "  [resume] Chopper: ${i} done, skipping."; continue; }
        gunzip -c 01_reads/${i}.fastq.gz | chopper -q 12 -l 300 --headcrop 20 --threads $THREADS_TOTAL | gzip > 02_filter/${i}.fastq.gz
    done

    log "Post-filtering QC..."
    for i in $(cat samples); do
        resume_done "02_filter/QC/${i}/NanoStats.txt" && continue
        MPLBACKEND=Agg NanoPlot --fastq 02_filter/${i}.fastq.gz -o 02_filter/QC/${i} --downsample 20000 --threads 4 --loglength &
    done
else
    log "Skipping preprocessing — using existing reads and QC from previous run."
    if [ ! -s "samples" ]; then
        error_log "'samples' file not found. Re-run without --skip-preprocessing first."
        exit 1
    fi
fi

[ "$STOP_AFTER" = "preprocessing" ] && { log "Done — stopping after preprocessing (--just-preprocessing). Filtered reads in 02_filter/."; exit 0; }

# 2. Taxonomy, assembly, polishing, and assembly QC
conda activate aluminion_assembly

if [ -z "$SKIP_KRAKEN" ]; then
    log "Taxonomy (Kraken2)..."
    cp ${KRAKEN_DB}/*.k2d /dev/shm/
    for i in $(cat samples); do
        resume_done "04_taxonomies/kraken2/${i}.report" && { log "  [resume] Kraken2: ${i} done, skipping."; continue; }
        kraken2 --memory-mapping --db /dev/shm --minimum-base-quality 10 --minimum-hit-groups 100 --output 04_taxonomies/kraken2/${i}.out --use-names --report 04_taxonomies/kraken2/${i}.report --gzip-compressed 02_filter/${i}.fastq.gz --threads $THREADS_TOTAL
    done
    rm -f /dev/shm/*.k2d
else
    log "Skipping Kraken2..."
fi

log "Assembly (Flye)..."
failed_assembly=()
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/assembly.fasta"; then
        log "  [resume] Flye: ${i} already assembled, skipping."
        continue
    fi
    if ! flye --nano-hq 02_filter/${i}.fastq.gz --threads $THREADS_TOTAL --out-dir 03_assemblies/${i}; then
        echo ""
        echo "  ┌──────────────────────────────────────────────────────────────────────┐"
        echo "  │  ASSEMBLY FAILED: ${i}                                               |"
        echo "  │  Flye could not assemble this sample (no disjointigs produced).      |"
        echo "  │                                                                      │"
        echo "  │  Options:                                                            │"
        echo "  │    1) Skip sample and continue with the rest                         │"
        echo "  │    2) Retry with --meta (for high-copy or fragmented assemblies)     │"
        echo "  │    3) Stop pipeline for manual inspection                            │"
        echo "  └──────────────────────────────────────────────────────────────────────┘"
        read -rp "  Choose [1/2/3]: " flye_choice
        case "$flye_choice" in
            1)
                error_log "Skipping sample ${i} — it will be excluded from all downstream steps."
                failed_assembly+=("$i")
                ;;
            2)
                log "Retrying Flye with --meta for sample ${i}..."
                rm -rf 03_assemblies/${i}
                if ! flye --nano-hq 02_filter/${i}.fastq.gz --threads $THREADS_TOTAL --out-dir 03_assemblies/${i} --meta; then
                    error_log "Flye --meta also failed for ${i}. Skipping sample."
                    failed_assembly+=("$i")
                else
                    log "Flye --meta succeeded for sample ${i}."
                fi
                ;;
            3)
                error_log "Pipeline stopped by user after assembly failure on sample ${i}."
                exit 1
                ;;
            *)
                error_log "Invalid choice. Stopping pipeline."
                exit 1
                ;;
        esac
    fi
done

if [ ${#failed_assembly[@]} -gt 0 ]; then
    log "Removing ${#failed_assembly[@]} failed sample(s) from pipeline: ${failed_assembly[*]}"
    for s in "${failed_assembly[@]}"; do
        sed -i "/^${s}$/d" samples
    done
fi

log "Polishing (minimap2 + dorado polish)..."
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/.polished"; then
        log "  [resume] Polishing: ${i} done, skipping."
        continue
    fi
    minimap2 -ax map-ont -t $THREADS_TOTAL 03_assemblies/${i}/assembly.fasta 02_filter/${i}.fastq.gz \
        | samtools sort -@ $THREADS_TOTAL -o 03_assemblies/${i}/${i}_aligned_reads.bam
    samtools index -@ $THREADS_TOTAL 03_assemblies/${i}/${i}_aligned_reads.bam
    if dorado polish --threads $THREADS_TOTAL --device cpu \
            03_assemblies/${i}/${i}_aligned_reads.bam \
            03_assemblies/${i}/assembly.fasta \
            --bacteria --ignore-read-groups \
            > 03_assemblies/${i}/polished_assembly.fasta 2>/dev/null; then
        mv 03_assemblies/${i}/polished_assembly.fasta 03_assemblies/${i}/assembly.fasta
        touch "03_assemblies/${i}/.polished"
    else
        warn "Polishing failed for ${i} (dorado polish requires basecaller model in BAM header). Assembly kept unpolished."
        failed_polish+=("$i")
        rm -f 03_assemblies/${i}/polished_assembly.fasta
    fi
    rm -f 03_assemblies/${i}/${i}_aligned_reads.bam 03_assemblies/${i}/${i}_aligned_reads.bam.bai
done

log "Deconcatenation & Recircularization..."
> 03_assemblies/deconcat.log
conda activate aluminion_assembly
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/deconcat/assembly_corr.fasta"; then
        log "  [resume] Deconcat: ${i} done, skipping."
        continue
    fi
    if python3 "$SCRIPTS_PATH/deconcat.py" --fasta_file 03_assemblies/${i}/assembly.fasta \
            --fastq_file 02_filter/${i}.fastq.gz \
            --out_path 03_assemblies/${i}/deconcat >> 03_assemblies/deconcat.log 2>&1 \
        && [ -f 03_assemblies/${i}/deconcat/assembly_corr.fasta ]; then
        cp 03_assemblies/${i}/deconcat/assembly_corr.fasta 03_assemblies/${i}.fasta
    else
        warn "Deconcat failed or produced no output for ${i}. Using assembly.fasta as-is."
        failed_deconcat+=("$i")
        cp 03_assemblies/${i}/assembly.fasta 03_assemblies/${i}.fasta 2>/dev/null || true
    fi
done
conda activate aluminion_circlator
for i in $(cat samples); do
    if resume_done "03_assemblies/${i}/.circlator_done"; then
        log "  [resume] Circlator: ${i} done, skipping."
        continue
    fi
    if circlator fixstart 03_assemblies/${i}.fasta 03_assemblies/${i}.fix 2>/dev/null; then
        mv 03_assemblies/${i}.fix.fasta 03_assemblies/${i}.fasta
        rm -f 03_assemblies/*fix* 03_assemblies/*fasta.*
        touch "03_assemblies/${i}/.circlator_done"
    else
        warn "Circlator fixstart failed for ${i}. Assembly kept without recircularization."
        failed_circlator+=("$i")
        rm -f 03_assemblies/${i}.fix* 2>/dev/null || true
    fi
done

log "Assembly QC..."
if resume_done "03_assemblies/quast/transposed_report.tsv"; then
    log "  [resume] QUAST: already done, skipping."
else
    quast.py -o 03_assemblies/quast -t $THREADS_TOTAL 03_assemblies/*.fasta
fi
for i in $(cat samples); do
    resume_done "03_assemblies/${i}.png" && continue
    Bandage image 03_assemblies/${i}/assembly_graph.gfa 03_assemblies/${i}.png --lengths --depth --toutline 1.0
done

[ "$STOP_AFTER" = "assembly" ] && { log "Done — stopping after assembly (--just-assembly). Assemblies in 03_assemblies/."; exit 0; }

# 3. Annotation
conda activate aluminion_annot

log "Annotation (Bakta)..."
for i in $(cat samples); do
    resume_done "08_Anotacion/${i}/${i}.gbff" && { log "  [resume] Bakta: ${i} done, skipping."; continue; }
    bakta --db $BAKTA_DB --output 08_Anotacion/${i} --threads $THREADS_TOTAL 03_assemblies/${i}.fasta --force
done

log "Plasmid Extraction (MOB-Suite Docker)..."
for i in $(cat samples); do
    resume_done "08_Anotacion/${i}/mob_recon" && { log "  [resume] MOB-suite: ${i} done, skipping."; continue; }
    docker run --rm -v $(pwd):/mnt/ --user $(id -u):$(id -g) "$MOBSUITE_IMAGE" mob_recon -i /mnt/03_assemblies/${i}.fasta -o /mnt/08_Anotacion/${i}/mob_recon -c --force -n $THREADS_TOTAL
done

if [ -z "$SKIP_ABR" ]; then
    log "AMR Screen (Abricate)..."
    for i in $(cat samples); do
        resume_done "08_Anotacion/${i}/abricate/${i}.tab" && { log "  [resume] Abricate: ${i} done, skipping."; continue; }
        mkdir -p 08_Anotacion/${i}/abricate
        abricate --minid 75 --mincov 75 03_assemblies/${i}.fasta > 08_Anotacion/${i}/abricate/${i}.tab
    done
    abricate --summary 08_Anotacion/*/abricate/*.tab > 08_Anotacion/AbR.tab
    cp 08_Anotacion/AbR.tab AbR_report.csv
else
    log "Skipping AMR Screen (Abricate)..."
fi

# Integrons
if [ -z "$SKIP_INTEGRONS" ]; then
    log "Running Integrons module (Integron_finder)..."
    conda activate aluminion_integron
    for i in $(cat samples); do
        resume_done "11_integrons/${i}" && { log "  [resume] Integron_Finder: ${i} done, skipping."; continue; }
        integron_finder 03_assemblies/${i}.fasta --cpu $THREADS_TOTAL --outdir 11_integrons/${i} --func-annot --gbk || true
    done
    conda activate aluminion_annot
    python3 "$SCRIPTS_PATH/integron_parser.py" .
    cp 11_integrons/integron_summary.csv . || true
else
    log "Skipping Integrons module..."
fi

# Plasmid typing (Copla — Docker only)
if [ -z "$SKIP_PLASMIDS" ]; then
    log "Running Plasmid Typing module (Copla)..."
    [ -z "$RESUME" ] && > copla.txt
    for j in $(cat samples); do
        if resume_done "08_Anotacion/${j}/copla"; then
            log "  [resume] Copla: ${j} done, skipping."
            continue
        fi
        find 08_Anotacion/${j}/mob_recon/ -name "*.fasta" -size -600k -size +1k | while read -r i; do
            new_name=$(basename "$i" | cut -d'_' -f1)
            cp "${i}" 05_plasmids/${new_name}_${j}.fasta
            echo "Sample: ${j}" && echo "Contig: ${i:(-11):5}" && docker run --rm -v $(pwd):/tmp "$COPLA_IMAGE" copla /tmp/"${i}" /data/app/databases/Copla_RS84/RS84f_sHSBM.pickle /data/app/databases/Copla_RS84/CoplaDB.fofn /tmp/08_Anotacion/${j}/copla
        done >> copla.txt 2>&1
    done
else
    log "Skipping Plasmid module (Copla)..."
fi

# Typing tools: GAMBIT + MLST + Kleborate + ECTyper
if [ -z "$SKIP_TYPING" ]; then
    log "Typing (GAMBIT, MLST, Kleborate, ECTyper)..."
    conda activate aluminion_annot
    if resume_done "04_taxonomies/gambit.csv"; then
        log "  [resume] GAMBIT: already done, skipping."
    else
        gambit -d $GAMBIT_DB query -o 04_taxonomies/gambit.csv 03_assemblies/*.fasta
    fi
    if resume_done "mlst.csv"; then
        log "  [resume] MLST: already done, skipping."
    else
        mlst 03_assemblies/*.fasta -q > mlst.csv
    fi
    conda activate aluminion_kleborate
    cp 03_assemblies/*.fasta 04_taxonomies/gtdb/
    if resume_done "04_taxonomies/kleborate/enterobacterales__species_output.txt"; then
        log "  [resume] Kleborate: already done, skipping."
    else
        kleborate -a 03_assemblies/*.fasta -o 04_taxonomies/kleborate -m enterobacterales__species,klebsiella_pneumo_complex__amr,klebsiella_pneumo_complex__kaptive,klebsiella_pneumo_complex__mlst,escherichia__mlst_achtman,klebsiella_pneumo_complex__resistance_score,klebsiella_pneumo_complex__resistance_gene_count,klebsiella__ybst,klebsiella__cbst,klebsiella__abst,klebsiella__smst,klebsiella__rmst,klebsiella__rmpa2,klebsiella_pneumo_complex__virulence_score
        cp 04_taxonomies/kleborate/enterobacterales__species_output.txt kleborate.tsv || true
    fi
    if resume_done "04_taxonomies/ectyper/output.tsv"; then
        log "  [resume] ECTyper: already done, skipping."
    else
        ectyper -i 04_taxonomies/gtdb -o 04_taxonomies/ectyper
    fi
    conda activate aluminion_annot
else
    log "Skipping Typing (GAMBIT, MLST, Kleborate, ECTyper)..."
fi


# 5. Phastest (Docker)
if [ -z "$SKIP_PHAGES" ]; then
    log "Running Phages module (Phastest)..."
    for i in $(cat samples); do
        if resume_done "09_phages/phastest_deep/${i}"; then
            log "  [resume] Phastest: ${i} done, skipping."
            continue
        fi
        mkdir -p 09_phages/phastest_deep/"$i"/
        cp 03_assemblies/"$i".fasta "${PHASTEST_DIR}/phastest_inputs/"
        docker compose -f "${PHASTEST_DIR}/docker-compose.yml" run --rm --user $(id -u):$(id -g) phastest -i fasta -m deep -s "$i".fasta --phage-only --yes
        cp -r "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i/"* 09_phages/phastest_deep/"$i"/ || true
        rm -rf "${PHASTEST_DIR}/phastest-app-docker/JOBS/$i" "${PHASTEST_DIR}/phastest_inputs/$i.fasta"
    done
    conda activate aluminion_annot
    python3 "$SCRIPTS_PATH/phage_parser.py" . 
    cp 09_phages/phage_summary.csv . || true
else
    log "Skipping Phages module..."
fi


# 6. Final Tables, IS, and consolidation (always aluminion_annot)
conda activate aluminion_annot
log "IS parsing and Final Tables..."
> IS.tsv
echo -e "sample\tmax\tIS_name\tTotal_IS" > IS.tsv
for i in $(cat samples); do
    if [ -f "08_Anotacion/${i}/mob_recon/chromosome.fasta" ]; then
        if ! resume_done "08_Anotacion/${i}/IS_chr_out.tsv"; then
            sed -i 's/>contig/>Chr/g' "08_Anotacion/${i}/mob_recon/chromosome.fasta"
            makeblastdb -in "08_Anotacion/${i}/mob_recon/chromosome.fasta" -dbtype nucl
            blastn -db "08_Anotacion/${i}/mob_recon/chromosome.fasta" -query "$ISFINDER_DB" -outfmt "6 qseqid sseqid sstart send pident mismatch evalue" | sort -k 3 > 08_Anotacion/${i}/IS_chr.tsv
            python3 "$SCRIPTS_PATH/IS_parser.py" -i 08_Anotacion/${i}
        else
            log "  [resume] IS search: ${i} done, skipping."
        fi
        cat 08_Anotacion/${i}/IS_chr_out.tsv | cut -f 2 | sort | uniq -c | sort -r | awk '{print $1"\t"$2}' > 08_Anotacion/${i}/N_IS_${i}.tsv
        MAX_IS=$(head -n 1 08_Anotacion/${i}/N_IS_${i}.tsv || echo -e "0\tNone")
        TOTAL_IS=$(tail -n +2 08_Anotacion/${i}/IS_chr_out.tsv | wc -l || echo "0")
        echo -e "${i}\t${MAX_IS}\t${TOTAL_IS}" >> IS.tsv
    fi
done

# Text parsing (Awk, Sed, Python)
for i in $(cat samples); do grep 'Median read length\|Median read quality\|Number of reads\|Total bases\|1:' 01_reads/QC/${i}/NanoStats.txt | cut -d ':' -f 2 | cut -d '(' -f 1 | column -t | datamash transpose; done > 01_reads/QC_reads.csv
paste samples 01_reads/QC_reads.csv > 01_reads/QC_reads_pre.csv
sed -i '1 i\Sample\tMedian length\tMedian quality\tTotal reads\tTotal bases\tMaxQ\tLongest read' 01_reads/QC_reads_pre.csv
cp 01_reads/QC_reads_pre.csv QC_reads_pre.csv 

for i in $(cat samples); do grep 'Median read length\|Median read quality\|Number of reads\|Total bases\|1:' 02_filter/QC/${i}/NanoStats.txt | cut -d ':' -f 2 | cut -d '(' -f 1 | column -t | datamash transpose; done > 02_filter/QC_reads.csv
paste samples 02_filter/QC_reads.csv > 02_filter/QC_reads_post.csv
sed -i '1 i\Sample\tMedian length\tMedian quality\tTotal reads\tTotal bases\tMaxQ\tLongest read' 02_filter/QC_reads_post.csv
cp 02_filter/QC_reads_post.csv QC_reads_post.csv 

paste QC_reads_pre.csv QC_reads_post.csv > QC_reads.csv; rm QC_reads_pre.csv QC_reads_post.csv 

> 04_taxonomies/kraken2/genus.csv
> 04_taxonomies/kraken2/species.csv
for i in $(cat samples); do
    awk '($1 >= 20 && $4 == "G")' 04_taxonomies/kraken2/${i}.report | cut -f 1,6 | tr -s '  ' | awk '{print i,"\t",$1,"\t",$2,$3,$4}' i="${i}" >> 04_taxonomies/kraken2/genus.csv || true
    awk '($1 >= 4  && $4 == "S")' 04_taxonomies/kraken2/${i}.report | cut -f 1,6 | tr -s '  ' | awk '{print i,"\t",$1,"\t",$2,$3,$4}' i="${i}" >> 04_taxonomies/kraken2/species.csv || true
done
awk -F"\t" 'NR==FNR{a[$1]=$0;next} ($1 in a){b=$1;$1="";print a[b] $0}' OFS="\t" 04_taxonomies/kraken2/genus.csv 04_taxonomies/kraken2/species.csv > 04_taxonomies/kraken_report.csv || true
sed -i '1 i\Sample\tReads(%)\tGenus\tReads(%)\tSpecies' 04_taxonomies/kraken_report.csv || true
sed 's/\t[[:blank:]]*/\t/g' 04_taxonomies/kraken_report.csv > kraken.csv || true

cut 03_assemblies/quast/transposed_report.tsv -f 1,14-17,26 > QC_assembly.csv
sed -i 's/Assembly/Samples/' QC_assembly.csv

log "Executing final consolidation in Python (Orchestrator)..."
python3 "$SCRIPTS_PATH/parser.py" -i . $SKIP_PHAGES $SKIP_INTEGRONS $SKIP_PLASMIDS $SKIP_TYPING $SKIP_KRAKEN $SKIP_ABR

log "Generating Interactive HTML Report..."
python3 "$SCRIPTS_PATH/aluminion_reporter.py" "$PWD"

log "Updating historical databases (data_seq.tsv / data_analysis.tsv)..."
python3 "$SCRIPTS_PATH/Datos_seq_unified2.py" --input_path . $INIT_DB

# Print a consolidated warning summary for all non-fatal failures
if [ ${#failed_polish[@]} -gt 0 ] || [ ${#failed_deconcat[@]} -gt 0 ] || [ ${#failed_circlator[@]} -gt 0 ]; then
    echo ""
    warn "========================================================================"
    warn "Pipeline finished with warnings — assemblies are valid but not fully"
    warn "refined for the following samples:"
    [ ${#failed_polish[@]}    -gt 0 ] && warn "  Unpolished  (dorado polish failed): ${failed_polish[*]}"
    [ ${#failed_deconcat[@]}  -gt 0 ] && warn "  Deconcatenation failed            : ${failed_deconcat[*]}"
    [ ${#failed_circlator[@]} -gt 0 ] && warn "  Not recircularized (circlator)    : ${failed_circlator[*]}"
    warn "========================================================================"
    echo ""
fi

log "Pipeline successfully finished. Aluminion out."