#!/usr/bin/env bash
# ==============================================================================
# Aluminion - Bacterial WGS Pipeline
# ==============================================================================

# 1. STRICT MODE: Stops the script on errors, undefined variables, or pipe failures
set -euo pipefail

# ==============================================================================
# 2. DEFAULT PARAMETERS
# ==============================================================================
THREADS_TOTAL=30
RUN_NAME=""
BASE_DIR="/home/usuario/Seqs/Servicio"
SEQ_LIST_INPUT=""

# Databases (Maintained as global constants)
KRAKEN_DB="/home/usuario/Databases/Kraken"
GAMBIT_DB="/home/usuario/Databases/gambit/"
BAKTA_DB="/home/usuario/Databases/bakta/db/"
MEGARES_DB="/home/usuario/Databases/megares/sequences"

# ==============================================================================
# 3. HELP AND LOGGING FUNCTIONS
# ==============================================================================
show_help() {
    cat << EOF

 Aluminion: Automated pipeline for bacterial genomes (Oxford Nanopore) 

Usage: ./aluminion.sh -r <run_name> [options]

Mandatory options:
  -r, --run       Name of the run folder generated by MinKNOW. 
                  (e.g., BAC_2025_NOV_25)

Additional options:
  -t, --threads   Number of threads/cores to use. (Default: 30)
  -l, --list      Path to the lista_seq.tsv file. If not provided, the script 
                  will look for it or create an empty one in the working directory.
  -d, --dir       Base working directory to save the analysis.
                  (Default: /home/usuario/Seqs/Servicio)
  -h, --help      Show this help message and exit.

Example:
  ./aluminion.sh -r BAC_2025_NOV_25 -t 60 -l /home/usuario/Downloads/lista_seq.tsv

EOF
}

log() {
    echo -e "\n\033[1;32m[$(date +'%Y-%m-%d %H:%M:%S')] $1\033[0m"
}

error_log() {
    echo -e "\n\033[1;31m[ERROR] $1\033[0m"
}

# ==============================================================================
# 4. COMMAND LINE ARGUMENT PARSING
# ==============================================================================
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -r|--run) RUN_NAME="$2"; shift ;;
        -t|--threads) THREADS_TOTAL="$2"; shift ;;
        -l|--list) SEQ_LIST_INPUT="$2"; shift ;;
        -d|--dir) BASE_DIR="$2"; shift ;;
        -h|--help) show_help; exit 0 ;;
        *) error_log "Unknown parameter: $1"; show_help; exit 1 ;;
    esac
    shift
done

# Mandatory parameter validation
if [ -z "$RUN_NAME" ]; then
    error_log "The -r / --run parameter is mandatory."
    show_help
    exit 1
fi

# Define the final working directory
WORKDIR="${BASE_DIR}/${RUN_NAME}"

# ==============================================================================
# 5. CONDA INITIALIZATION
# ==============================================================================
if [ -f "$HOME/mambaforge/etc/profile.d/conda.sh" ]; then
    source "$HOME/mambaforge/etc/profile.d/conda.sh"
elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
else
    error_log "Could not find conda.sh initialization script."
    exit 1
fi

# ==============================================================================
# 6. DIRECTORY AND DATA PREPARATION
# ==============================================================================
log "Starting Aluminion for run: $RUN_NAME"
mkdir -p "$WORKDIR"
cd "$WORKDIR"

log "Copying base data from MinKNOW..."
cp -r /var/lib/minknow/data/$RUN_NAME/no_sample_id/*/fastq_pass/ . || true
cp /var/lib/minknow/data/$RUN_NAME/no_sample_id/*/final_summary_*.txt . || true
cp /var/lib/minknow/data/$RUN_NAME/no_sample_id/*/report_*.json . || true

# --- lista_seq.tsv MANAGEMENT ---
if [ -n "$SEQ_LIST_INPUT" ]; then
    if [ ! -f "$SEQ_LIST_INPUT" ]; then
        error_log "The file provided in --list ($SEQ_LIST_INPUT) does not exist."
        exit 1
    fi
    log "Copying sequencing list from $SEQ_LIST_INPUT..."
    cp "$SEQ_LIST_INPUT" "lista_seq.tsv"
fi

if [ ! -f "lista_seq.tsv" ]; then
    # Header kept in Spanish to avoid breaking downstream Python parsers
    echo -e "Cultivo\tCepario\tID\tBarcode\tConcDNA\tRepetir" > lista_seq.tsv
    error_log "An empty 'lista_seq.tsv' has been created in $WORKDIR. Fill it out and re-run Aluminion."
    exit 1
fi

log "Creating directory structure..."
mkdir -p 01_reads/QC 02_filter/QC 03_assemblies/quast 04_taxonomies/{kraken2,gtdb} 05_plasmids 08_Anotacion 09_phages 10_ices 11_integrons ../repositorio/{01_reads,03_assemblies,05_plasmids,08_Anotacion,09_phages,10_ices,11_integrons}

log "Renaming and consolidating FASTQs..."
echo -e "ID\tR1\tR2\tLongFastQ\tFast5\tGenomeSize\tFasta" > samplesheet.tsv 

tail -n +2 lista_seq.tsv | while IFS=$'\t' read -r cult cep id bc c rep; do
    [ -z "$id" ] && continue 
    
    if [ -z "$rep" ]; then
        log "Processing $id (New sample)"
        cat fastq_pass/barcode${bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
    else
        log "Processing $id (Repeated sample - Concatenating)"
        cat ../repositorio/01_reads/${id}.fastq.gz fastq_pass/barcode${bc}/*.fastq.gz > 01_reads/${id}.fastq.gz
    fi
    cp 01_reads/${id}.fastq.gz ../repositorio/01_reads/${id}.fastq.gz
    echo -e "${id}\t\t\t$PWD/01_reads/${id}.fastq.gz\t\t" >> samplesheet.tsv
done

cut -f3 lista_seq.tsv | tail -n+2 > ../repositorio/samples

# Filter by size > 135M and save to 'samples'
find 01_reads -type f -name "*.fastq.gz" -size +135M -exec basename {} .fastq.gz \; | sort | uniq > samples

if [ ! -s samples ]; then
    error_log "No samples passed the 135MB size filter. Aborting."
    exit 1
fi

# ==============================================================================
# 7. READ PREPROCESSING AND QC
# ==============================================================================
conda activate minion

log "Pre-filtering Quality Control (NanoPlot)..."
for i in $(cat samples); do
    NanoPlot --fastq 01_reads/${i}.fastq.gz -o 01_reads/QC/${i} --downsample 20000 --loglength --threads 3 &
done
wait

log "Read Filtering (Chopper)..."
for i in $(cat samples); do
    gunzip -c 01_reads/${i}.fastq.gz | chopper -q 12 -l 300 --headcrop 20 --threads $THREADS_TOTAL | gzip > 02_filter/${i}.fastq.gz
done 

log "Post-filtering Quality Control (NanoPlot)..."
for i in $(cat samples); do
    NanoPlot --fastq 02_filter/${i}.fastq.gz -o 02_filter/QC/${i} --downsample 20000 --loglength --threads 3 & 
done
wait

log "Read Taxonomy (Kraken2 on RAM)..."
cp ${KRAKEN_DB}/*.k2d /dev/shm/
for i in $(cat samples); do 
    kraken2 --memory-mapping --db /dev/shm --minimum-base-quality 10 --minimum-hit-groups 100 --output 04_taxonomies/kraken2/${i}.out --use-names --report 04_taxonomies/kraken2/${i}.report --gzip-compressed 02_filter/${i}.fastq.gz --threads $THREADS_TOTAL
done 
rm /dev/shm/*.k2d

# ==============================================================================
# 8. ASSEMBLY AND POLISHING
# ==============================================================================
log "De novo Assembly (Flye)..."
for i in $(cat samples); do 
    flye --nano-hq 02_filter/${i}.fastq.gz --threads $THREADS_TOTAL --out-dir 03_assemblies/${i}
done

log "Multimer Deconcatenation..."
conda activate deconcat
> 03_assemblies/deconcat.log
for i in $(cat samples); do 
    log "Deconcatenating $i"
    python3 /home/usuario/Seqs/Servicio/Scripts/deconcat/deconcat.py --fasta_file 03_assemblies/${i}/assembly.fasta --fastq_file 02_filter/${i}.fastq.gz --out_path 03_assemblies/${i}/deconcat >> 03_assemblies/deconcat.log 2>&1 || true
    cp 03_assemblies/${i}/deconcat/assembly_corr.fasta 03_assemblies/${i}.fasta
done 

log "Recircularization (Circlator)..."
conda activate nano
for i in $(cat samples); do 
    circlator fixstart 03_assemblies/${i}.fasta 03_assemblies/${i}.fix
    mv 03_assemblies/${i}.fix.fasta 03_assemblies/${i}.fasta
    rm -f 03_assemblies/*fix* 03_assemblies/*fasta.*
done

log "Assembly QC (QUAST and Bandage)..."
/home/usuario/Programs/quast-5.2.0/quast.py -o 03_assemblies/quast -t $THREADS_TOTAL --glimmer --rna-finding --conserved-genes-finding --plots-format png 03_assemblies/*.fasta

for i in $(cat samples); do 
    Bandage image 03_assemblies/${i}/assembly_graph.gfa 03_assemblies/${i}.png --lengths --depth --fontsize 4 --nodseglen 10 --nodelen 150 --toutline 1.0
done

# ==============================================================================
# 9. ANNOTATION AND CLASSIFICATION
# ==============================================================================
log "Assembly Taxonomy (GAMBIT)..."
conda activate gambit
gambit -d $GAMBIT_DB query -o 04_taxonomies/gambit.csv 03_assemblies/*.fasta 
cp 03_assemblies/*.fasta 04_taxonomies/gtdb/

log "Genome Annotation (Bakta)..."
conda activate minion
for i in $(cat samples); do 
    bakta --db $BAKTA_DB --verbose --output 08_Anotacion/${i} --threads $THREADS_TOTAL 03_assemblies/${i}.fasta --force
done

log "Plasmid Extraction (MOB-Suite)..."
for i in $(cat samples); do
    docker run --rm -v $(pwd):/mnt/ --user $(id -u):$(id -g) "kbessonov/mob_suite:3.0.3" mob_recon -i /mnt/03_assemblies/${i}.fasta -t -o /mnt/08_Anotacion/${i}/mob_recon -c --force -n $THREADS_TOTAL
done

log "Integron Search (Integron_finder)..."
conda activate covidion
for i in $(cat samples); do
    integron_finder 03_assemblies/${i}.fasta --cpu $THREADS_TOTAL --outdir 11_integrons/${i} --func-annot --gbk || true
done

conda activate integron_parser
python3 ../Scripts/integrones/integron_parser.py .
cp 11_integrons/integron_summary.csv . || true

log "Plasmid Typing (Copla)..."
conda activate copla
echo "Copla results" > copla.txt
for j in $(cat samples); do
    find 08_Anotacion/${j}/mob_recon/ -name "*.fasta" -size -600k -size +1k | while read -r i; do
        new_name=$(basename "$i" | cut -d'_' -f1)
        cp "${i}" 05_plasmids/${new_name}_${j}.fasta
        echo "Sample: ${j} - Contig: ${new_name}"
        python3 ~/Programs/copla/bin/copla.py "${i}" /home/usuario/Programs/copla/databases/Copla_RS84/RS84f_sHSBM.pickle /home/usuario/Programs/copla/databases/Copla_RS84/CoplaDB.fofn 08_Anotacion/${j}/copla
    done >> copla.txt 2>&1
done

log "AMR Gene Detection (Abricate)..."
conda activate abr
for i in $(cat samples); do
    mkdir -p 08_Anotacion/${i}/abricate
    abricate --minid 75 --mincov 75 03_assemblies/${i}.fasta > 08_Anotacion/${i}/abricate/${i}.tab
done
abricate --summary 08_Anotacion/*/abricate/*.tab > 08_Anotacion/AbR.tab

log "Multilocus Sequence Typing (MLST)..."
conda activate mlst
mlst 03_assemblies/*.fasta -q > mlst.csv

log "Specific Typing (Kleborate and ECTyper)..."
conda activate kleborate
kleborate -a 03_assemblies/*.fasta -o 04_taxonomies/kleborate -m enterobacterales__species,klebsiella_pneumo_complex__amr,klebsiella_pneumo_complex__kaptive,klebsiella_pneumo_complex__mlst,escherichia__mlst_achtman,klebsiella_pneumo_complex__resistance_score,klebsiella_pneumo_complex__resistance_gene_count,klebsiella__ybst,klebsiella__cbst,klebsiella__abst,klebsiella__smst,klebsiella__rmst,klebsiella__rmpa2,klebsiella_pneumo_complex__virulence_score
cp klebsiellas/enterobacterales__species_output.txt kleborate.tsv || true

conda activate kleb
ectyper -i 04_taxonomies/gtdb -o 04_taxonomies/ectyper

log "Phage Detection (Phastest)..."
for i in $(cat samples); do
    mkdir -p 09_phages/phastest_deep/"$i"/
    cp 03_assemblies/"$i".fasta /home/usuario/Programs/phastest-docker/phastest_inputs/
    docker compose -f /home/usuario/Programs/phastest-docker/docker-compose.yml down --remove-orphans
    docker compose -f /home/usuario/Programs/phastest-docker/docker-compose.yml run --user $(id -u):$(id -g) phastest -i fasta -m deep -s "$i".fasta --phage-only --yes
    
    cp -r /home/usuario/Programs/phastest-docker/phastest-app-docker/JOBS/"$i"/* 09_phages/phastest_deep/"$i"/ || true
    rm -rf /home/usuario/Programs/phastest-docker/phastest-app-docker/JOBS/"$i"
    rm -f /home/usuario/Programs/phastest-docker/phastest_inputs/"$i".fasta
done

conda activate minion
python3 /home/usuario/Seqs/Servicio/Scripts/phages/phage_parser.py . 
cp 09_phages/phage_summary.csv . || true

# ==============================================================================
# 10. INSERTION SEQUENCES AND FINAL TABLES
# ==============================================================================
log "Processing Insertion Sequences (IS)..."
conda activate nano
> IS.tsv
echo -e "sample\tmax\tIS_name\tTotal_IS" > IS.tsv

for i in $(cat samples); do 
    CHROM_FASTA="08_Anotacion/${i}/mob_recon/chromosome.fasta"
    if [ -f "$CHROM_FASTA" ]; then
        sed -i 's/>contig/>Chr/g' "$CHROM_FASTA"
        makeblastdb -in "$CHROM_FASTA" -dbtype nucl
        blastn -db "$CHROM_FASTA" -query /home/usuario/Databases/ISfinder/ISfinder-nucl.fasta -outfmt "6 qseqid sseqid sstart send pident mismatch evalue" | sort -k 3 > 08_Anotacion/${i}/IS_chr.tsv
        python3 /home/usuario/Seqs/Servicio/IS_parser.py -i 08_Anotacion/${i}
        
        cat 08_Anotacion/${i}/IS_chr_out.tsv | cut -f 2 | sort | uniq -c | sort -r | awk '{print $1"\t"$2}' > 08_Anotacion/${i}/N_IS_${i}.tsv
        
        MAX_IS=$(head -n 1 08_Anotacion/${i}/N_IS_${i}.tsv || echo -e "0\tNone")
        TOTAL_IS=$(tail -n +2 08_Anotacion/${i}/IS_chr_out.tsv | wc -l || echo "0")
        
        echo -e "${i}\t${MAX_IS}\t${TOTAL_IS}" >> IS.tsv
    fi
done

log "Generating summary tables..."
for i in $(cat samples); do 
    grep 'Median read length\|Median read quality\|Number of reads\|Total bases\|1:' 01_reads/QC/${i}/NanoStats.txt | cut -d ':' -f 2 | cut -d '(' -f 1 | column -t | datamash transpose
done > 01_reads/QC_reads.csv
paste samples 01_reads/QC_reads.csv > 01_reads/QC_reads_pre.csv
sed -i '1 i\Sample\tMedian length\tMedian quality\tTotal reads\tTotal bases\tMaxQ\tLongest read' 01_reads/QC_reads_pre.csv
cp 01_reads/QC_reads_pre.csv QC_reads_pre.csv 

for i in $(cat samples); do
    grep 'Median read length\|Median read quality\|Number of reads\|Total bases\|1:' 02_filter/QC/${i}/NanoStats.txt | cut -d ':' -f 2 | cut -d '(' -f 1 | column -t | datamash transpose
done > 02_filter/QC_reads.csv
paste samples 02_filter/QC_reads.csv > 02_filter/QC_reads_post.csv
sed -i '1 i\Sample\tMedian length\tMedian quality\tTotal reads\tTotal bases\tMaxQ\tLongest read' 02_filter/QC_reads_post.csv
cp 02_filter/QC_reads_post.csv QC_reads_post.csv 

paste QC_reads_pre.csv QC_reads_post.csv > QC_reads.csv
rm QC_reads_pre.csv QC_reads_post.csv 

for i in $(cat samples); do  
    awk '($1 >= 20 && $4 == "G")' 04_taxonomies/kraken2/${i}.report | cut -f 1,6 | tr -s '  ' | awk '{print i,"\t",$1,"\t",$2,$3,$4}' i="${i}" >> 04_taxonomies/kraken2/genus.csv || true
    awk '($1 >= 4  && $4 == "S")' 04_taxonomies/kraken2/${i}.report | cut -f 1,6 | tr -s '  ' | awk '{print i,"\t",$1,"\t",$2,$3,$4}' i="${i}" >> 04_taxonomies/kraken2/species.csv || true
done 
awk -F"\t" 'NR==FNR{a[$1]=$0;next} ($1 in a){b=$1;$1="";print a[b] $0}' OFS="\t" 04_taxonomies/kraken2/genus.csv 04_taxonomies/kraken2/species.csv > 04_taxonomies/kraken_report.csv || true
sed -i '1 i\Sample\tReads(%)\tGenus\tReads(%)\tSpecies' 04_taxonomies/kraken_report.csv || true
sed 's/\t[[:blank:]]*/\t/g' 04_taxonomies/kraken_report.csv > kraken.csv || true

cut 03_assemblies/quast/transposed_report.tsv -f 1,14-17,26 > QC_assembly.csv
sed -i 's/Assembly/Samples/' QC_assembly.csv

log "Executing final consolidation in Python..."
conda activate minion
python3 /home/usuario/Seqs/Servicio/Scripts/parser.py -i .
python3 ../Scripts/Datos_seq_unified2.py --input_path .

log "Pipeline successfully finished. Aluminion out."
