#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# =============================================================================
# Script:  mge_alerts.py
# Purpose: Compare mobile genetic elements (plasmids, integrons) detected in
#          the current Aluminion run against the cumulative MGE repository
#          and emit an alerts table whenever a recurrent or clinically
#          relevant element is found.
# Input:   - Current run directory (must contain parser.py outputs:
#            data_analysis.tsv, copla_modif.csv, integron_summary.csv)
#          - Repository path (initialized via mge_repository.Repository.init)
# Output:  - <run>/alerts.tsv
#          - <run>/Alerts_Report.html (generated by alerts_reporter.py, P4)
# Author:  Aluminion lab
# Date:    2026-05-20
# =============================================================================

"""Cross-run MGE alert generator.

The alert pipeline runs in three phases:

1. Ingest the current run into the repository (plasmids + integrons + host
   metadata). This grows the repository before matching so that re-running
   the alerts on the same run is idempotent.
2. For every MGE in the current run, search the *prior* repository state for
   matches (plasmid: two-level tuple + ANI; integron: Jaccard on cassette
   gene set).
3. Apply the relevance filter (AMR or virulence genes carried, with priority
   escalation for carbapenemases / mcr / hypervirulence and for cross-species
   transfer) and emit ``alerts.tsv``.

This file is the scaffold for P0; the matching and reporting bodies land in
P3 / P4.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import Counter
from pathlib import Path

import pandas as pd

from _priority_genes import classify_priority
from mge_repository import (
    MIN_PLASMID_SIZE,
    Repository,
    deserialize_gene_set,
    make_host_uid,
    now_iso,
    serialize_gene_set,
)


# -----------------------------------------------------------------------------
# Alert table schema — single source of truth for the output columns.
# -----------------------------------------------------------------------------
ALERTS_COLUMNS: list[str] = [
    "alert_category",          # RECURRENT_RELEVANT | NEW_PRIORITY
    "priority",                # high | medium
    "mge_type",                # plasmid | integron
    "current_host_uid",
    "current_lab_id",
    "current_isolate_id",
    "current_species",
    "current_mlst",
    "match_uid",               # repository UID matched (empty for NEW_PRIORITY)
    "match_level",             # type | identity (plasmid) or jaccard:0.85 (integron)
    "previous_host_uid",
    "previous_species",
    "previous_mlst",
    "previous_amr_genes",
    "cross_species",           # yes | no
    "ptu",
    "mob",
    "mpf",
    "rep",
    "size",
    "gene_set",                # integron cassette gene set (JSON)
    "amr_genes",
    "vir_genes",
    "priority_genes_detected", # subset of amr_genes/vir_genes that hit HIGH
    "priority_categories",     # comma-joined: carbapenemase,mcr,hv_klebsiella,esbl
    "n_prior_occurrences",
]


def parse_arguments() -> argparse.Namespace:
    """CLI parser. Kept close to ``parser.py`` style for consistency."""
    ap = argparse.ArgumentParser(
        prog="mge_alerts.py",
        description=(
            "Compare MGEs in the current run against the cumulative "
            "repository and emit cross-run alerts."
        ),
    )
    ap.add_argument(
        "--run-dir",
        required=True,
        type=Path,
        help="Path to the current Aluminion run directory (the one that "
             "contains data_analysis.tsv after parser.py).",
    )
    ap.add_argument(
        "--repo",
        required=True,
        type=Path,
        help="Path to the MGE repository (initialize with --init-repo on "
             "aluminion.sh, or via mge_repository.Repository.init()).",
    )
    ap.add_argument(
        "--run-name",
        required=True,
        help="Stable identifier for the current run; used to build host UIDs "
             "(e.g. the basename of the run directory or a date-stamped tag).",
    )
    ap.add_argument(
        "--alert-new-priority",
        action="store_true",
        help="In addition to recurrent matches, raise NEW_PRIORITY alerts for "
             "first-occurrence MGEs that carry HIGH-priority genes "
             "(carbapenemase, mcr, hypervirulence).",
    )
    ap.add_argument(
        "--no-ingest",
        action="store_true",
        help="Skip ingestion of the current run into the repository. Useful "
             "for ad-hoc lookups or for running the alerts in dry-run mode.",
    )
    ap.add_argument(
        "--ani-threshold",
        type=float,
        default=99.0,
        help="Minimum ANI (%%) for a plasmid identity-level match (default: 99.0).",
    )
    ap.add_argument(
        "--jaccard-threshold",
        type=float,
        default=0.8,
        help="Minimum Jaccard index for an integron cassette-set match (default: 0.8).",
    )
    ap.add_argument(
        "--size-tolerance",
        type=float,
        default=0.15,
        help="Plasmid size tolerance (fractional) for tuple-level matching "
             "(default: 0.15).",
    )
    ap.add_argument(
        "--min-plasmid-size",
        type=int,
        default=MIN_PLASMID_SIZE,
        help=f"Skip plasmids smaller than this many bp (default: {MIN_PLASMID_SIZE}).",
    )
    return ap.parse_args()


# -----------------------------------------------------------------------------
# Ingestion helpers
# -----------------------------------------------------------------------------
def _parse_cassette_gene_set(row: pd.Series) -> set[str]:
    """Extract the unique gene names from an integron_summary.csv row.

    Each ``Cassette N`` cell is a Python list literal (e.g.
    ``"['blaOXA-1_1']"``); each list item is a string of the form
    ``"<gene>;<description>"``. We keep only the leading ``<gene>`` token to
    build a comparable cassette gene set. Cells that are empty, ``"-"`` or
    unparseable are silently skipped.
    """
    genes: set[str] = set()
    for col, val in row.items():
        if not isinstance(col, str) or not col.startswith("Cassette "):
            continue
        if not val or val == "-":
            continue
        try:
            items = ast.literal_eval(val)
        except (ValueError, SyntaxError):
            continue
        if not isinstance(items, list):
            continue
        for item in items:
            if not isinstance(item, str):
                continue
            # Items can be e.g. "blaOXA-1_1" or "aphA;Aminoglycoside ...";
            # we only want the gene name.
            name = item.split(";")[0].strip()
            if name:
                genes.add(name)
    return genes


def _load_virulence_by_sample(run_dir: Path) -> dict[str, str]:
    """Build ``{sample_id -> virulence_genes_string}`` from VF_modif.xlsx.

    Returns an empty dict if the file does not exist. The ``#FILE`` column
    in VF_modif.xlsx already contains the bare sample ID after parser.py
    processes it (e.g., ``"Kpne_VC_175-1"``), so no extra path stripping is
    needed.
    """
    vf_path = run_dir / "VF_modif.xlsx"
    if not vf_path.exists():
        return {}
    try:
        df = pd.read_excel(vf_path, keep_default_na=False)
    except Exception as exc:  # broad: openpyxl can raise many exotic errors
        print(f"[mge_alerts] could not read {vf_path}: {exc}", file=sys.stderr)
        return {}
    if "#FILE" not in df.columns or "Virulence_genes" not in df.columns:
        return {}
    return dict(zip(df["#FILE"].astype(str), df["Virulence_genes"].astype(str)))


def _load_run_inputs(run_dir: Path) -> dict:
    """Load the run-level inputs that both matching and ingestion need.

    Returns a dict ``{data_analysis, copla, integrons, vir_by_sample}``.
    Missing optional inputs (copla, integron_summary, VF_modif) yield empty
    frames / dicts; only ``data_analysis.tsv`` is required.

    Host metadata is merged from two sources:
      * ``data_analysis.tsv`` provides ``Lab_id``, ``ID``, ``Barcode`` and
        ``Strain`` (the lab-tracking columns).
      * ``taxonomy.csv``      provides ``Majority_genus``, ``Majority_species``,
        ``Subspecies``, ``MLST``, ``Serotype``, ``KO_locus``, ``AMRscore``
        and ``VIRscore`` — these are typically populated by parser.py while
        ``data_analysis.tsv`` keeps them as a placeholder until
        lab_db_updater.py merges them in the cumulative DB.

    The merge is a left-join on ``data_analysis.ID == taxonomy.Sample`` so
    every sample present in ``data_analysis.tsv`` keeps a row even when
    taxonomy.csv has not been emitted yet (e.g. in --skip-typing runs).
    """
    data_analysis_path = run_dir / "data_analysis.tsv"
    if not data_analysis_path.exists():
        raise FileNotFoundError(
            f"{data_analysis_path} not found. Run parser.py first or pass a "
            "different --run-dir."
        )
    data_analysis = pd.read_csv(data_analysis_path, sep="\t", dtype=str).fillna("")

    taxonomy_path = run_dir / "taxonomy.csv"
    if taxonomy_path.exists():
        taxonomy = pd.read_csv(taxonomy_path, sep=",", dtype=str).fillna("")
        # Columns where taxonomy.csv is authoritative — overwrite the
        # data_analysis placeholder values when both exist.
        tax_cols = [
            "Majority_genus", "Majority_species", "Subspecies", "MLST",
            "Serotype", "KO_locus", "AMRscore", "VIRscore",
        ]
        present = ["Sample"] + [c for c in tax_cols if c in taxonomy.columns]
        merged = data_analysis.merge(
            taxonomy[present], how="left",
            left_on="ID", right_on="Sample", suffixes=("", "_tax"),
        )
        for c in tax_cols:
            tax_col = f"{c}_tax"
            if tax_col in merged.columns:
                # Prefer taxonomy.csv values; fall back to data_analysis ones.
                merged[c] = merged[tax_col].where(
                    merged[tax_col].astype(bool), merged.get(c, "")
                )
                merged.drop(columns=[tax_col], inplace=True)
        if "Sample" in merged.columns:
            merged.drop(columns=["Sample"], inplace=True)
        data_analysis = merged.fillna("")

    copla_path = run_dir / "copla_modif.csv"
    copla = (
        pd.read_csv(copla_path, sep=",", dtype=str).fillna("")
        if copla_path.exists()
        else pd.DataFrame()
    )
    integrons_path = run_dir / "integron_summary.csv"
    integrons = (
        pd.read_csv(integrons_path, sep=",", dtype=str).fillna("")
        if integrons_path.exists()
        else pd.DataFrame()
    )
    return {
        "data_analysis": data_analysis,
        "copla": copla,
        "integrons": integrons,
        "vir_by_sample": _load_virulence_by_sample(run_dir),
    }


def run_ingestion(args: argparse.Namespace, repo: Repository) -> dict:
    """Ingest plasmids, integrons and host metadata of the current run.

    The function is tolerant to missing optional inputs: copla_modif.csv
    and integron_summary.csv are optional (their absence is logged and
    skipped), but data_analysis.tsv is required because host metadata is
    the backbone of every cross-run alert.
    """
    run_dir: Path = args.run_dir
    run_name: str = args.run_name

    inputs = _load_run_inputs(run_dir)
    data_analysis = inputs["data_analysis"]
    copla = inputs["copla"]
    integrons = inputs["integrons"]
    vir_by_sample = inputs["vir_by_sample"]

    n_hosts = n_plasmids = n_integrons = 0
    n_plasmids_skipped_size = 0
    n_plasmids_skipped_missing = 0

    # ---- Hosts ----------------------------------------------------------
    for _, row in data_analysis.iterrows():
        isolate_id = row.get("ID", "")
        if not isolate_id:
            continue
        host_uid = make_host_uid(run_name, isolate_id)
        repo.ingest_host({
            "host_uid": host_uid,
            "run_name": run_name,
            "lab_id": row.get("Lab_id", ""),
            "isolate_id": isolate_id,
            "strain": row.get("Strain", ""),
            "genus": row.get("Majority_genus", ""),
            "species": row.get("Majority_species", ""),
            "subspecies": row.get("Subspecies", ""),
            "mlst": row.get("MLST", ""),
            "serotype": row.get("Serotype", ""),
            "ko_locus": row.get("KO_locus", ""),
            "amr_score": row.get("AMRscore", ""),
            "vir_score": row.get("VIRscore", ""),
            "ingested_at": now_iso(),
        })
        n_hosts += 1

    # ---- Plasmids -------------------------------------------------------
    # MOB-suite emits per-plasmid FASTAs as
    #   08_Anotacion/<sample>/mob_recon/plasmid_<cluster_id>.fasta
    # and the Copla output uses the cluster_id as the "Contig" column. The
    # chromosome and unbinned contigs are intentionally ignored (the user
    # tracks chromosomal AMR via Kleborate / ABRicate on the assembly).
    for _, row in copla.iterrows():
        isolate_id = row.get("Sample", "")
        contig = row.get("Contig", "")
        if not isolate_id or not contig:
            continue
        try:
            size = int(row.get("Size", "0") or 0)
        except ValueError:
            size = 0
        if size and size < args.min_plasmid_size:
            n_plasmids_skipped_size += 1
            continue
        host_uid = make_host_uid(run_name, isolate_id)
        fasta = (
            run_dir / "08_Anotacion" / isolate_id / "mob_recon"
            / f"plasmid_{contig}.fasta"
        )
        uid = repo.ingest_plasmid(
            host_uid, contig, fasta,
            metadata={
                "run_name": run_name,
                "sample_id": isolate_id,
                "ptu": row.get("PTU", ""),
                "rep": row.get("Rep", ""),
                "mob": row.get("MOB", ""),
                "mpf": row.get("MPF", ""),
                "size": size,
                "amr_genes": row.get("AbR", ""),
                "vir_genes": vir_by_sample.get(isolate_id, ""),
            },
        )
        if uid is None:
            n_plasmids_skipped_missing += 1
        else:
            n_plasmids += 1

    # ---- Integrons ------------------------------------------------------
    # Each row of integron_summary.csv is one integron on one contig of one
    # sample. Cassette columns give the (ordered) gene list which we collapse
    # into an unordered set for Jaccard matching (P3 decision).
    for _, row in integrons.iterrows():
        isolate_id = row.get("Sample", "")
        contig = row.get("Pl/Chr", "")
        try:
            start = int(row.get("Start", "0") or 0)
            end = int(row.get("End", "0") or 0)
        except ValueError:
            continue
        if not isolate_id or not contig or start <= 0 or end <= 0:
            continue

        host_uid = make_host_uid(run_name, isolate_id)
        gene_set = _parse_cassette_gene_set(row)
        # Integrons are AMR-bearing by construction in clinical isolates;
        # we mirror the cassette gene set into amr_genes so the P4 relevance
        # filter can read a single uniform field across MGE types.
        amr_genes_str = ";".join(sorted(gene_set))

        assembly = run_dir / "03_assemblies" / f"{isolate_id}.fasta"
        uid = repo.ingest_integron(
            host_uid, contig, start, end, assembly,
            metadata={
                "run_name": run_name,
                "sample_id": isolate_id,
                "integron_type": row.get("Type", ""),
                "integrase": row.get("Integrase", ""),
                "gene_set_json": serialize_gene_set(gene_set),
                "amr_genes": amr_genes_str,
                "vir_genes": "",
            },
        )
        if uid is not None:
            n_integrons += 1

    # ---- Sketch rebuild -------------------------------------------------
    repo.update_plasmid_sketch()

    return {
        "hosts": n_hosts,
        "plasmids": n_plasmids,
        "plasmids_skipped_size": n_plasmids_skipped_size,
        "plasmids_skipped_missing_fasta": n_plasmids_skipped_missing,
        "integrons": n_integrons,
    }


def run_matching(args: argparse.Namespace, repo: Repository) -> list[dict]:
    """Match each MGE of the current run against the repository's prior state.

    Must be called *before* :func:`run_ingestion` so the repo snapshot does
    not contain the current run yet (otherwise every plasmid would trivially
    match itself). Returns a list of match-record dicts; one record per
    ``(current_mge, repo_mge)`` pair. P4 consumes these to apply the
    relevance filter and emit ``alerts.tsv``.

    Plasmids are matched at two levels: tuple-coarse (same PTU/Rep/MOB and
    size within ``args.size_tolerance``) and identity-fine (skani ANI
    >= ``args.ani_threshold``). A UID that fires at the identity level is
    labeled ``"identity"``; UIDs that fire only at the tuple level are
    labeled ``"type"``. Integrons are matched only by Jaccard on the
    cassette gene set (>= ``args.jaccard_threshold``).
    """
    run_dir: Path = args.run_dir
    run_name: str = args.run_name

    inputs = _load_run_inputs(run_dir)
    data_analysis = inputs["data_analysis"]
    copla = inputs["copla"]
    integrons = inputs["integrons"]
    vir_by_sample = inputs["vir_by_sample"]

    # Current-run host metadata indexed by isolate ID for quick lookup when
    # building match records. Same shape as hosts.tsv but in memory and
    # restricted to the current run.
    current_hosts: dict[str, dict] = {}
    for _, row in data_analysis.iterrows():
        isolate_id = row.get("ID", "")
        if not isolate_id:
            continue
        current_hosts[isolate_id] = {
            "host_uid": make_host_uid(run_name, isolate_id),
            "run_name": run_name,
            "lab_id": row.get("Lab_id", ""),
            "isolate_id": isolate_id,
            "genus": row.get("Majority_genus", ""),
            "species": row.get("Majority_species", ""),
            "subspecies": row.get("Subspecies", ""),
            "mlst": row.get("MLST", ""),
            "serotype": row.get("Serotype", ""),
            "ko_locus": row.get("KO_locus", ""),
            "amr_score": row.get("AMRscore", ""),
            "vir_score": row.get("VIRscore", ""),
        }

    repo_hosts = repo.load_hosts().set_index("host_uid", drop=False) if not repo.load_hosts().empty else None

    records: list[dict] = []

    # ---- Plasmid matching ----------------------------------------------
    for _, row in copla.iterrows():
        isolate_id = row.get("Sample", "")
        contig = row.get("Contig", "")
        if not isolate_id or not contig:
            continue
        try:
            size = int(row.get("Size", "0") or 0)
        except ValueError:
            size = 0
        if size and size < args.min_plasmid_size:
            continue

        current_meta = {
            "ptu": row.get("PTU", ""),
            "rep": row.get("Rep", ""),
            "mob": row.get("MOB", ""),
            "mpf": row.get("MPF", ""),
            "size": size,
            "amr_genes": row.get("AbR", ""),
            "vir_genes": vir_by_sample.get(isolate_id, ""),
        }

        # Tuple-level matches.
        df_tuple = repo.find_plasmid_matches_by_tuple(
            current_meta["ptu"], current_meta["rep"], current_meta["mob"],
            size, size_tolerance=args.size_tolerance,
        )
        tuple_uids = set(df_tuple["uid"]) if not df_tuple.empty else set()

        # Identity-level matches via skani. Query FASTA is the MOB-suite
        # output from the current run (not yet ingested into the repo).
        query_fasta = (
            run_dir / "08_Anotacion" / isolate_id / "mob_recon"
            / f"plasmid_{contig}.fasta"
        )
        df_ani = repo.find_plasmid_matches_by_ani(
            query_fasta, min_ani=args.ani_threshold,
        )
        identity_uids = set(df_ani["uid"]) if not df_ani.empty else set()
        ani_by_uid = (
            dict(zip(df_ani["uid"], df_ani["ani"])) if not df_ani.empty else {}
        )

        all_uids = tuple_uids | identity_uids
        for uid in all_uids:
            # Identity wins over type when a UID fires at both levels.
            if uid in identity_uids:
                level = "identity"
                score = float(ani_by_uid.get(uid, 0.0))
            else:
                level = "type"
                score = 1.0
            repo_row = (
                df_ani[df_ani["uid"] == uid].iloc[0].to_dict()
                if uid in identity_uids
                else df_tuple[df_tuple["uid"] == uid].iloc[0].to_dict()
            )
            repo_host_row = (
                repo_hosts.loc[repo_row["host_uid"]].to_dict()
                if (repo_hosts is not None and repo_row["host_uid"] in repo_hosts.index)
                else {}
            )
            records.append({
                "mge_type": "plasmid",
                "current_isolate_id": isolate_id,
                "current_contig": contig,
                "current_host": current_hosts.get(isolate_id, {}),
                "current_meta": current_meta,
                "match_uid": uid,
                "match_level": level,
                "score": score,
                "repo_row": repo_row,
                "repo_host": repo_host_row,
            })

    # ---- Integron matching ---------------------------------------------
    for _, row in integrons.iterrows():
        isolate_id = row.get("Sample", "")
        contig = row.get("Pl/Chr", "")
        try:
            start = int(row.get("Start", "0") or 0)
            end = int(row.get("End", "0") or 0)
        except ValueError:
            continue
        if not isolate_id or not contig or start <= 0 or end <= 0:
            continue
        gene_set = _parse_cassette_gene_set(row)
        if not gene_set:
            continue

        df_j = repo.find_integron_matches_by_jaccard(
            gene_set, min_jaccard=args.jaccard_threshold,
        )
        if df_j.empty:
            continue

        current_meta = {
            "integron_type": row.get("Type", ""),
            "integrase": row.get("Integrase", ""),
            "gene_set": sorted(gene_set),
            "gene_set_json": serialize_gene_set(gene_set),
            "amr_genes": ";".join(sorted(gene_set)),  # cassettes are AMR-bearing
            "vir_genes": "",
            "size": end - start + 1,
            "start": start,
            "end": end,
        }

        for _, jrow in df_j.iterrows():
            repo_host_row = (
                repo_hosts.loc[jrow["host_uid"]].to_dict()
                if (repo_hosts is not None and jrow["host_uid"] in repo_hosts.index)
                else {}
            )
            records.append({
                "mge_type": "integron",
                "current_isolate_id": isolate_id,
                "current_contig": contig,
                "current_host": current_hosts.get(isolate_id, {}),
                "current_meta": current_meta,
                "match_uid": jrow["uid"],
                "match_level": f"jaccard:{jrow['jaccard']:.2f}",
                "score": float(jrow["jaccard"]),
                "repo_row": jrow.to_dict(),
                "repo_host": repo_host_row,
            })

    return records


# -----------------------------------------------------------------------------
# Alert emission (P4)
# -----------------------------------------------------------------------------
# Regex that strips trailing identity/coverage annotations like " (99.50)" or
# " (100.00;98.95)" that VF_modif.xlsx attaches to each gene name. Applied
# before classify_priority() so the regex catalog operates on bare gene names.
_SCORE_SUFFIX_RE = re.compile(r"\s*\([^)]*\)\s*$")


def _split_gene_string(s: str) -> set[str]:
    """Normalize an AMR/VIR gene field into a set of bare gene names.

    Handles both Copla's semicolon list (``"OXA-48;CTX-M-15"``) and the
    comma-separated list with score annotations emitted by parser.py for
    VFDB (``"fimH (98.50), rmpA (100.00)"``).
    """
    if not s or s == "-":
        return set()
    parts = re.split(r"[;,]", s)
    out: set[str] = set()
    for p in parts:
        p = _SCORE_SUFFIX_RE.sub("", p).strip()
        if p and p != "-":
            out.add(p)
    return out


def _species_token(s: str) -> str:
    """Extract the bare species (or genus) epithet from a Majority_* field.

    ``data_analysis.tsv`` stores values such as ``"pneumoniae (95.3%)"`` or
    ``"Klebsiella (95.3%)"``; we keep only the first whitespace-delimited
    token so that cross-species comparisons are stable.
    """
    if not s:
        return ""
    return s.strip().split()[0]


def _is_cross_species(match: dict) -> bool:
    """True if the current and prior hosts belong to different species OR
    different genera. Returns False when either side has unknown taxonomy
    (empty species and empty genus) — conservative: no taxonomic info means
    we cannot claim a cross-species event.
    """
    cur = match.get("current_host", {})
    pri = match.get("repo_host", {})
    cur_sp = _species_token(cur.get("species", ""))
    pri_sp = _species_token(pri.get("species", ""))
    cur_gn = _species_token(cur.get("genus", ""))
    pri_gn = _species_token(pri.get("genus", ""))

    species_known = cur_sp and pri_sp
    genus_known = cur_gn and pri_gn
    if not species_known and not genus_known:
        return False
    if species_known and cur_sp != pri_sp:
        return True
    if genus_known and cur_gn != pri_gn:
        return True
    return False


def _format_genes(values) -> str:
    """Join a gene iterable with semicolons in a stable order for the TSV."""
    if isinstance(values, str):
        return values
    return ";".join(sorted({v for v in values if v}))


def _build_alert_row(
    *,
    category: str,
    priority: str,
    match: dict | None,
    current_isolate_id: str,
    current_meta: dict,
    current_host: dict,
    mge_type: str,
    cross_species: bool,
    priority_info: dict,
    amr_genes: set[str],
    vir_genes: set[str],
    n_prior_occurrences: int,
) -> dict:
    """Assemble a single alerts.tsv row matching :data:`ALERTS_COLUMNS`."""
    repo_row = (match or {}).get("repo_row", {}) or {}
    repo_host = (match or {}).get("repo_host", {}) or {}

    if mge_type == "plasmid":
        ptu = current_meta.get("ptu", "")
        mob = current_meta.get("mob", "")
        mpf = current_meta.get("mpf", "")
        rep = current_meta.get("rep", "")
        size = current_meta.get("size", "")
        gene_set = ""
    else:
        ptu = mob = mpf = rep = ""
        size = current_meta.get("size", "")
        gene_set = current_meta.get("gene_set_json", "[]")

    return {
        "alert_category": category,
        "priority": priority,
        "mge_type": mge_type,
        "current_host_uid": current_host.get("host_uid", ""),
        "current_lab_id": current_host.get("lab_id", ""),
        "current_isolate_id": current_isolate_id,
        "current_species": current_host.get("species", ""),
        "current_mlst": current_host.get("mlst", ""),
        "match_uid": (match or {}).get("match_uid", ""),
        "match_level": (match or {}).get("match_level", ""),
        "previous_host_uid": repo_row.get("host_uid", ""),
        "previous_species": repo_host.get("species", ""),
        "previous_mlst": repo_host.get("mlst", ""),
        "previous_amr_genes": repo_row.get("amr_genes", ""),
        "cross_species": "yes" if cross_species else "no",
        "ptu": ptu,
        "mob": mob,
        "mpf": mpf,
        "rep": rep,
        "size": str(size) if size != "" else "",
        "gene_set": gene_set,
        "amr_genes": _format_genes(amr_genes),
        "vir_genes": _format_genes(vir_genes),
        "priority_genes_detected": ";".join(sorted(set(priority_info.get("matched", [])))),
        "priority_categories": ",".join(priority_info.get("categories", [])),
        "n_prior_occurrences": str(n_prior_occurrences),
    }


def emit_alerts(
    matches: list[dict],
    args: argparse.Namespace,
    repo: Repository,
) -> Path:
    """Build ``alerts.tsv`` from match records and optional NEW_PRIORITY scan.

    Returns the path of the written file. Even when no alerts fire, the file
    is written with the header row so downstream consumers (HTML reporter,
    notification systems) can always rely on its presence.
    """
    rows: list[dict] = []

    # ----- RECURRENT_RELEVANT ----------------------------------------------
    # Count how many prior repo entries each current MGE matched. The same
    # number is replicated across every row sharing the (isolate, contig)
    # key so the analyst can see "this plasmid has been seen N times".
    prior_counts: Counter[tuple[str, str]] = Counter(
        (m["current_isolate_id"], m["current_contig"]) for m in matches
    )

    for m in matches:
        amr = _split_gene_string(m["current_meta"].get("amr_genes", ""))
        vir = _split_gene_string(m["current_meta"].get("vir_genes", ""))
        if not amr and not vir:
            # Match exists but the MGE is not epidemiologically relevant
            # (no AMR / no virulence). Skip per the agreed trigger rule.
            continue

        info = classify_priority(amr | vir)
        cross = _is_cross_species(m)
        # Priority escalation: HIGH if either a HIGH-priority gene fires
        # or the match crosses a species boundary.
        priority = "high" if (info["priority"] == "high" or cross) else "medium"

        rows.append(_build_alert_row(
            category="RECURRENT_RELEVANT",
            priority=priority,
            match=m,
            current_isolate_id=m["current_isolate_id"],
            current_meta=m["current_meta"],
            current_host=m["current_host"],
            mge_type=m["mge_type"],
            cross_species=cross,
            priority_info=info,
            amr_genes=amr,
            vir_genes=vir,
            n_prior_occurrences=prior_counts[(m["current_isolate_id"], m["current_contig"])],
        ))

    # ----- NEW_PRIORITY ----------------------------------------------------
    if args.alert_new_priority:
        matched_keys = {(m["current_isolate_id"], m["current_contig"]) for m in matches}
        inputs = _load_run_inputs(args.run_dir)
        run_name: str = args.run_name

        # Plasmids: any current plasmid not matched in repo, carrying a
        # HIGH-priority gene (carbapenemase / mcr / hypervirulence) and
        # passing the size cut.
        for _, row in inputs["copla"].iterrows():
            isolate_id = row.get("Sample", "")
            contig = row.get("Contig", "")
            if not isolate_id or not contig:
                continue
            if (isolate_id, contig) in matched_keys:
                continue
            try:
                size = int(row.get("Size", "0") or 0)
            except ValueError:
                size = 0
            if size and size < args.min_plasmid_size:
                continue

            amr = _split_gene_string(row.get("AbR", ""))
            vir = _split_gene_string(inputs["vir_by_sample"].get(isolate_id, ""))
            info = classify_priority(amr | vir)
            if info["priority"] != "high":
                continue

            current_host = {
                "host_uid": make_host_uid(run_name, isolate_id),
                "lab_id": "",
                "isolate_id": isolate_id,
                "species": "",
                "mlst": "",
            }
            # Backfill from data_analysis.tsv when present (same shape as
            # run_matching builds it).
            da = inputs["data_analysis"]
            da_row = da[da["ID"] == isolate_id]
            if not da_row.empty:
                r0 = da_row.iloc[0]
                current_host["lab_id"] = r0.get("Lab_id", "")
                current_host["species"] = r0.get("Majority_species", "")
                current_host["mlst"] = r0.get("MLST", "")

            rows.append(_build_alert_row(
                category="NEW_PRIORITY",
                priority="high",
                match=None,
                current_isolate_id=isolate_id,
                current_meta={
                    "ptu": row.get("PTU", ""),
                    "rep": row.get("Rep", ""),
                    "mob": row.get("MOB", ""),
                    "mpf": row.get("MPF", ""),
                    "size": size,
                },
                current_host=current_host,
                mge_type="plasmid",
                cross_species=False,
                priority_info=info,
                amr_genes=amr,
                vir_genes=vir,
                n_prior_occurrences=0,
            ))

        # Integrons: any current integron not matched in repo whose cassette
        # gene set carries a HIGH-priority gene.
        for _, row in inputs["integrons"].iterrows():
            isolate_id = row.get("Sample", "")
            contig = row.get("Pl/Chr", "")
            if not isolate_id or not contig:
                continue
            if (isolate_id, contig) in matched_keys:
                continue
            gene_set = _parse_cassette_gene_set(row)
            if not gene_set:
                continue

            info = classify_priority(gene_set)
            if info["priority"] != "high":
                continue

            try:
                start = int(row.get("Start", "0") or 0)
                end = int(row.get("End", "0") or 0)
            except ValueError:
                start = end = 0

            current_host = {
                "host_uid": make_host_uid(run_name, isolate_id),
                "lab_id": "",
                "isolate_id": isolate_id,
                "species": "",
                "mlst": "",
            }
            da_row = inputs["data_analysis"][
                inputs["data_analysis"]["ID"] == isolate_id
            ]
            if not da_row.empty:
                r0 = da_row.iloc[0]
                current_host["lab_id"] = r0.get("Lab_id", "")
                current_host["species"] = r0.get("Majority_species", "")
                current_host["mlst"] = r0.get("MLST", "")

            rows.append(_build_alert_row(
                category="NEW_PRIORITY",
                priority="high",
                match=None,
                current_isolate_id=isolate_id,
                current_meta={
                    "size": end - start + 1 if start and end else "",
                    "gene_set_json": serialize_gene_set(gene_set),
                },
                current_host=current_host,
                mge_type="integron",
                cross_species=False,
                priority_info=info,
                amr_genes=gene_set,
                vir_genes=set(),
                n_prior_occurrences=0,
            ))

    # ----- Write TSV --------------------------------------------------------
    out = pd.DataFrame(rows, columns=ALERTS_COLUMNS).fillna("")
    # Stable sort: HIGH first, then MEDIUM, then by mge_type and isolate_id.
    priority_order = {"high": 0, "medium": 1}
    if not out.empty:
        out["_psort"] = out["priority"].map(priority_order).fillna(99)
        out = (
            out.sort_values(["_psort", "mge_type", "current_isolate_id"])
            .drop(columns=["_psort"])
            .reset_index(drop=True)
        )

    alerts_path: Path = args.run_dir / "alerts.tsv"
    out.to_csv(alerts_path, sep="\t", index=False)
    return alerts_path


def main(argv: list[str] | None = None) -> int:
    args = parse_arguments() if argv is None else parse_arguments()

    repo = Repository.open(args.repo)
    print(
        f"[mge_alerts] run={args.run_name}  repo={args.repo}",
        file=sys.stderr,
    )

    # Matching MUST happen before ingestion so that the current run's own
    # plasmids/integrons are not matched against themselves.
    matches = run_matching(args, repo)
    print(
        f"[mge_alerts] matching produced {len(matches)} match record(s) "
        "(grouped/filtered in P4 → alerts.tsv).",
        file=sys.stderr,
    )

    if not args.no_ingest:
        stats = run_ingestion(args, repo)
        print(
            "[mge_alerts] ingestion stats: "
            f"hosts={stats['hosts']}  plasmids={stats['plasmids']}  "
            f"plasmids_skipped_size={stats['plasmids_skipped_size']}  "
            f"plasmids_skipped_missing_fasta={stats['plasmids_skipped_missing_fasta']}  "
            f"integrons={stats['integrons']}",
            file=sys.stderr,
        )

    alerts_path = emit_alerts(matches, args, repo)
    n_alerts = sum(1 for _ in open(alerts_path)) - 1  # subtract header
    print(
        f"[mge_alerts] wrote {n_alerts} alert(s) to {alerts_path}",
        file=sys.stderr,
    )

    # HTML report — lazy import so the script still runs in environments
    # without the optional jinja templating (currently we use pure f-string
    # rendering so this is just a normal import).
    try:
        from alerts_reporter import render_alerts_html
        html_path = args.run_dir / "Alerts_Report.html"
        render_alerts_html(alerts_path, html_path, run_name=args.run_name)
        print(f"[mge_alerts] wrote HTML report to {html_path}", file=sys.stderr)
    except Exception as exc:  # report failure is non-fatal
        print(f"[mge_alerts] HTML report generation failed: {exc}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
